# Required values:
provider: zpa # substitute the name of your provider, without the pulumi- prefix
#env: # A map of required configuration for any integration tests, etc.
#  AN_OPTION: value
#  ANOTHER_OPTION: true
  # etc.
lint: true # Linting should be true in most cases, unless failing rules in the upstream provider makes this impractical.

# Optional values:
#docker: true # Whether the provider's tests use Docker to run. If set to true, a file `testing/docker-compose.yml` must be present in the provider repository.
#setup-script: testing/setup.sh # Path to a script that's used for testing bootstraps