# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetUserPortalControllerResult',
    'AwaitableGetUserPortalControllerResult',
    'get_user_portal_controller',
    'get_user_portal_controller_output',
]

@pulumi.output_type
class GetUserPortalControllerResult:
    """
    A collection of values returned by getUserPortalController.
    """
    def __init__(__self__, certificate_id=None, certificate_name=None, creation_time=None, description=None, domain=None, enabled=None, ext_domain=None, ext_domain_name=None, ext_domain_translation=None, ext_label=None, getc_name=None, id=None, image_data=None, managed_by_zs=None, microtenant_id=None, microtenant_name=None, modified_by=None, modified_time=None, name=None, user_notification=None, user_notification_enabled=None):
        if certificate_id and not isinstance(certificate_id, str):
            raise TypeError("Expected argument 'certificate_id' to be a str")
        pulumi.set(__self__, "certificate_id", certificate_id)
        if certificate_name and not isinstance(certificate_name, str):
            raise TypeError("Expected argument 'certificate_name' to be a str")
        pulumi.set(__self__, "certificate_name", certificate_name)
        if creation_time and not isinstance(creation_time, str):
            raise TypeError("Expected argument 'creation_time' to be a str")
        pulumi.set(__self__, "creation_time", creation_time)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if domain and not isinstance(domain, str):
            raise TypeError("Expected argument 'domain' to be a str")
        pulumi.set(__self__, "domain", domain)
        if enabled and not isinstance(enabled, bool):
            raise TypeError("Expected argument 'enabled' to be a bool")
        pulumi.set(__self__, "enabled", enabled)
        if ext_domain and not isinstance(ext_domain, str):
            raise TypeError("Expected argument 'ext_domain' to be a str")
        pulumi.set(__self__, "ext_domain", ext_domain)
        if ext_domain_name and not isinstance(ext_domain_name, str):
            raise TypeError("Expected argument 'ext_domain_name' to be a str")
        pulumi.set(__self__, "ext_domain_name", ext_domain_name)
        if ext_domain_translation and not isinstance(ext_domain_translation, str):
            raise TypeError("Expected argument 'ext_domain_translation' to be a str")
        pulumi.set(__self__, "ext_domain_translation", ext_domain_translation)
        if ext_label and not isinstance(ext_label, str):
            raise TypeError("Expected argument 'ext_label' to be a str")
        pulumi.set(__self__, "ext_label", ext_label)
        if getc_name and not isinstance(getc_name, str):
            raise TypeError("Expected argument 'getc_name' to be a str")
        pulumi.set(__self__, "getc_name", getc_name)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if image_data and not isinstance(image_data, str):
            raise TypeError("Expected argument 'image_data' to be a str")
        pulumi.set(__self__, "image_data", image_data)
        if managed_by_zs and not isinstance(managed_by_zs, bool):
            raise TypeError("Expected argument 'managed_by_zs' to be a bool")
        pulumi.set(__self__, "managed_by_zs", managed_by_zs)
        if microtenant_id and not isinstance(microtenant_id, str):
            raise TypeError("Expected argument 'microtenant_id' to be a str")
        pulumi.set(__self__, "microtenant_id", microtenant_id)
        if microtenant_name and not isinstance(microtenant_name, str):
            raise TypeError("Expected argument 'microtenant_name' to be a str")
        pulumi.set(__self__, "microtenant_name", microtenant_name)
        if modified_by and not isinstance(modified_by, str):
            raise TypeError("Expected argument 'modified_by' to be a str")
        pulumi.set(__self__, "modified_by", modified_by)
        if modified_time and not isinstance(modified_time, str):
            raise TypeError("Expected argument 'modified_time' to be a str")
        pulumi.set(__self__, "modified_time", modified_time)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if user_notification and not isinstance(user_notification, str):
            raise TypeError("Expected argument 'user_notification' to be a str")
        pulumi.set(__self__, "user_notification", user_notification)
        if user_notification_enabled and not isinstance(user_notification_enabled, bool):
            raise TypeError("Expected argument 'user_notification_enabled' to be a bool")
        pulumi.set(__self__, "user_notification_enabled", user_notification_enabled)

    @_builtins.property
    @pulumi.getter(name="certificateId")
    def certificate_id(self) -> _builtins.str:
        return pulumi.get(self, "certificate_id")

    @_builtins.property
    @pulumi.getter(name="certificateName")
    def certificate_name(self) -> _builtins.str:
        return pulumi.get(self, "certificate_name")

    @_builtins.property
    @pulumi.getter(name="creationTime")
    def creation_time(self) -> _builtins.str:
        return pulumi.get(self, "creation_time")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def domain(self) -> _builtins.str:
        return pulumi.get(self, "domain")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="extDomain")
    def ext_domain(self) -> _builtins.str:
        return pulumi.get(self, "ext_domain")

    @_builtins.property
    @pulumi.getter(name="extDomainName")
    def ext_domain_name(self) -> _builtins.str:
        return pulumi.get(self, "ext_domain_name")

    @_builtins.property
    @pulumi.getter(name="extDomainTranslation")
    def ext_domain_translation(self) -> _builtins.str:
        return pulumi.get(self, "ext_domain_translation")

    @_builtins.property
    @pulumi.getter(name="extLabel")
    def ext_label(self) -> _builtins.str:
        return pulumi.get(self, "ext_label")

    @_builtins.property
    @pulumi.getter(name="getcName")
    def getc_name(self) -> _builtins.str:
        return pulumi.get(self, "getc_name")

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="imageData")
    def image_data(self) -> _builtins.str:
        return pulumi.get(self, "image_data")

    @_builtins.property
    @pulumi.getter(name="managedByZs")
    def managed_by_zs(self) -> _builtins.bool:
        return pulumi.get(self, "managed_by_zs")

    @_builtins.property
    @pulumi.getter(name="microtenantId")
    def microtenant_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "microtenant_id")

    @_builtins.property
    @pulumi.getter(name="microtenantName")
    def microtenant_name(self) -> _builtins.str:
        return pulumi.get(self, "microtenant_name")

    @_builtins.property
    @pulumi.getter(name="modifiedBy")
    def modified_by(self) -> _builtins.str:
        return pulumi.get(self, "modified_by")

    @_builtins.property
    @pulumi.getter(name="modifiedTime")
    def modified_time(self) -> _builtins.str:
        return pulumi.get(self, "modified_time")

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="userNotification")
    def user_notification(self) -> _builtins.str:
        return pulumi.get(self, "user_notification")

    @_builtins.property
    @pulumi.getter(name="userNotificationEnabled")
    def user_notification_enabled(self) -> _builtins.bool:
        return pulumi.get(self, "user_notification_enabled")


class AwaitableGetUserPortalControllerResult(GetUserPortalControllerResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetUserPortalControllerResult(
            certificate_id=self.certificate_id,
            certificate_name=self.certificate_name,
            creation_time=self.creation_time,
            description=self.description,
            domain=self.domain,
            enabled=self.enabled,
            ext_domain=self.ext_domain,
            ext_domain_name=self.ext_domain_name,
            ext_domain_translation=self.ext_domain_translation,
            ext_label=self.ext_label,
            getc_name=self.getc_name,
            id=self.id,
            image_data=self.image_data,
            managed_by_zs=self.managed_by_zs,
            microtenant_id=self.microtenant_id,
            microtenant_name=self.microtenant_name,
            modified_by=self.modified_by,
            modified_time=self.modified_time,
            name=self.name,
            user_notification=self.user_notification,
            user_notification_enabled=self.user_notification_enabled)


def get_user_portal_controller(id: Optional[_builtins.str] = None,
                               microtenant_id: Optional[_builtins.str] = None,
                               name: Optional[_builtins.str] = None,
                               opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetUserPortalControllerResult:
    """
    * [Official documentation](https://help.zscaler.com/zpa/about-user-portals)
    * [API documentation](https://help.zscaler.com/zpa/about-user-portals)

    The **zpa_user_portal_controller** data source to get information about a user portal in the Zscaler Private Access cloud.

    ## Example Usage

    ### With Customer Own Certificate

    ```python
    import pulumi
    import pulumi_zpa as zpa
    import zscaler_pulumi_zpa as zpa

    this = zpa.get_ba_certificate(name="example.acme.com")
    this_user_portal_controller = zpa.UserPortalController("this",
        name="UserPortal01",
        description="UserPortal01",
        enabled=True,
        user_notification="User_Portal_Terraform_01",
        user_notification_enabled=True,
        certificate_id=this.id,
        domain="portal01")
    ```

    ### With Zscaler Managed Certificate

    ```python
    import pulumi
    import pulumi_zpa as zpa

    this = zpa.get_user_portal_controller(name="UserPortal01")
    ```
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['microtenantId'] = microtenant_id
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('zpa:index/getUserPortalController:getUserPortalController', __args__, opts=opts, typ=GetUserPortalControllerResult).value

    return AwaitableGetUserPortalControllerResult(
        certificate_id=pulumi.get(__ret__, 'certificate_id'),
        certificate_name=pulumi.get(__ret__, 'certificate_name'),
        creation_time=pulumi.get(__ret__, 'creation_time'),
        description=pulumi.get(__ret__, 'description'),
        domain=pulumi.get(__ret__, 'domain'),
        enabled=pulumi.get(__ret__, 'enabled'),
        ext_domain=pulumi.get(__ret__, 'ext_domain'),
        ext_domain_name=pulumi.get(__ret__, 'ext_domain_name'),
        ext_domain_translation=pulumi.get(__ret__, 'ext_domain_translation'),
        ext_label=pulumi.get(__ret__, 'ext_label'),
        getc_name=pulumi.get(__ret__, 'getc_name'),
        id=pulumi.get(__ret__, 'id'),
        image_data=pulumi.get(__ret__, 'image_data'),
        managed_by_zs=pulumi.get(__ret__, 'managed_by_zs'),
        microtenant_id=pulumi.get(__ret__, 'microtenant_id'),
        microtenant_name=pulumi.get(__ret__, 'microtenant_name'),
        modified_by=pulumi.get(__ret__, 'modified_by'),
        modified_time=pulumi.get(__ret__, 'modified_time'),
        name=pulumi.get(__ret__, 'name'),
        user_notification=pulumi.get(__ret__, 'user_notification'),
        user_notification_enabled=pulumi.get(__ret__, 'user_notification_enabled'))
def get_user_portal_controller_output(id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                      microtenant_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                      name: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                      opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetUserPortalControllerResult]:
    """
    * [Official documentation](https://help.zscaler.com/zpa/about-user-portals)
    * [API documentation](https://help.zscaler.com/zpa/about-user-portals)

    The **zpa_user_portal_controller** data source to get information about a user portal in the Zscaler Private Access cloud.

    ## Example Usage

    ### With Customer Own Certificate

    ```python
    import pulumi
    import pulumi_zpa as zpa
    import zscaler_pulumi_zpa as zpa

    this = zpa.get_ba_certificate(name="example.acme.com")
    this_user_portal_controller = zpa.UserPortalController("this",
        name="UserPortal01",
        description="UserPortal01",
        enabled=True,
        user_notification="User_Portal_Terraform_01",
        user_notification_enabled=True,
        certificate_id=this.id,
        domain="portal01")
    ```

    ### With Zscaler Managed Certificate

    ```python
    import pulumi
    import pulumi_zpa as zpa

    this = zpa.get_user_portal_controller(name="UserPortal01")
    ```
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['microtenantId'] = microtenant_id
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('zpa:index/getUserPortalController:getUserPortalController', __args__, opts=opts, typ=GetUserPortalControllerResult)
    return __ret__.apply(lambda __response__: GetUserPortalControllerResult(
        certificate_id=pulumi.get(__response__, 'certificate_id'),
        certificate_name=pulumi.get(__response__, 'certificate_name'),
        creation_time=pulumi.get(__response__, 'creation_time'),
        description=pulumi.get(__response__, 'description'),
        domain=pulumi.get(__response__, 'domain'),
        enabled=pulumi.get(__response__, 'enabled'),
        ext_domain=pulumi.get(__response__, 'ext_domain'),
        ext_domain_name=pulumi.get(__response__, 'ext_domain_name'),
        ext_domain_translation=pulumi.get(__response__, 'ext_domain_translation'),
        ext_label=pulumi.get(__response__, 'ext_label'),
        getc_name=pulumi.get(__response__, 'getc_name'),
        id=pulumi.get(__response__, 'id'),
        image_data=pulumi.get(__response__, 'image_data'),
        managed_by_zs=pulumi.get(__response__, 'managed_by_zs'),
        microtenant_id=pulumi.get(__response__, 'microtenant_id'),
        microtenant_name=pulumi.get(__response__, 'microtenant_name'),
        modified_by=pulumi.get(__response__, 'modified_by'),
        modified_time=pulumi.get(__response__, 'modified_time'),
        name=pulumi.get(__response__, 'name'),
        user_notification=pulumi.get(__response__, 'user_notification'),
        user_notification_enabled=pulumi.get(__response__, 'user_notification_enabled')))
