# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['TagNamespaceArgs', 'TagNamespace']

@pulumi.input_type
class TagNamespaceArgs:
    def __init__(__self__, *,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 microtenant_id: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 origin: Optional[pulumi.Input[_builtins.str]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a TagNamespace resource.
        :param pulumi.Input[_builtins.str] description: Description of the tag namespace
        :param pulumi.Input[_builtins.bool] enabled: Whether this tag namespace is enabled
        :param pulumi.Input[_builtins.str] microtenant_id: Microtenant ID
        :param pulumi.Input[_builtins.str] name: Name of the tag namespace
        :param pulumi.Input[_builtins.str] origin: Origin of the tag namespace. Defaults to CUSTOM
        :param pulumi.Input[_builtins.str] type: Type of the tag namespace. Defaults to STATIC
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if microtenant_id is not None:
            pulumi.set(__self__, "microtenant_id", microtenant_id)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if origin is not None:
            pulumi.set(__self__, "origin", origin)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Description of the tag namespace
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether this tag namespace is enabled
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="microtenantId")
    def microtenant_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Microtenant ID
        """
        return pulumi.get(self, "microtenant_id")

    @microtenant_id.setter
    def microtenant_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "microtenant_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the tag namespace
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def origin(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Origin of the tag namespace. Defaults to CUSTOM
        """
        return pulumi.get(self, "origin")

    @origin.setter
    def origin(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "origin", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Type of the tag namespace. Defaults to STATIC
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "type", value)


@pulumi.input_type
class _TagNamespaceState:
    def __init__(__self__, *,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 microtenant_id: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 origin: Optional[pulumi.Input[_builtins.str]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering TagNamespace resources.
        :param pulumi.Input[_builtins.str] description: Description of the tag namespace
        :param pulumi.Input[_builtins.bool] enabled: Whether this tag namespace is enabled
        :param pulumi.Input[_builtins.str] microtenant_id: Microtenant ID
        :param pulumi.Input[_builtins.str] name: Name of the tag namespace
        :param pulumi.Input[_builtins.str] origin: Origin of the tag namespace. Defaults to CUSTOM
        :param pulumi.Input[_builtins.str] type: Type of the tag namespace. Defaults to STATIC
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if microtenant_id is not None:
            pulumi.set(__self__, "microtenant_id", microtenant_id)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if origin is not None:
            pulumi.set(__self__, "origin", origin)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Description of the tag namespace
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether this tag namespace is enabled
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="microtenantId")
    def microtenant_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Microtenant ID
        """
        return pulumi.get(self, "microtenant_id")

    @microtenant_id.setter
    def microtenant_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "microtenant_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the tag namespace
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def origin(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Origin of the tag namespace. Defaults to CUSTOM
        """
        return pulumi.get(self, "origin")

    @origin.setter
    def origin(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "origin", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Type of the tag namespace. Defaults to STATIC
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "type", value)


@pulumi.type_token("zpa:index/tagNamespace:TagNamespace")
class TagNamespace(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 microtenant_id: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 origin: Optional[pulumi.Input[_builtins.str]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        The **zpa_tag_namespace** resource creates and manages tag namespaces in Zscaler Private Access (ZPA).

        > NOTE: This an Early Access feature.

        ## Example Usage

        ```python
        import pulumi
        import zscaler_pulumi_zpa as zpa

        this = zpa.TagNamespace("this",
            name="Example Namespace",
            description="An example tag namespace",
            enabled=True)
        ```

        ## Import

        Zscaler offers a dedicated tool called Zscaler-Terraformer to allow the automated import of ZPA configurations into Terraform-compliant HashiCorp Configuration Language.
        Visit

        **zpa_tag_namespace** can be imported by using `<TAG NAMESPACE ID>` or `<TAG NAMESPACE NAME>` as the import ID.

        For example:

        ```sh
        $ pulumi import zpa:index/tagNamespace:TagNamespace example <tag_namespace_id>
        ```

        or

        ```sh
        $ pulumi import zpa:index/tagNamespace:TagNamespace example <tag_namespace_name>
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: Description of the tag namespace
        :param pulumi.Input[_builtins.bool] enabled: Whether this tag namespace is enabled
        :param pulumi.Input[_builtins.str] microtenant_id: Microtenant ID
        :param pulumi.Input[_builtins.str] name: Name of the tag namespace
        :param pulumi.Input[_builtins.str] origin: Origin of the tag namespace. Defaults to CUSTOM
        :param pulumi.Input[_builtins.str] type: Type of the tag namespace. Defaults to STATIC
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[TagNamespaceArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        The **zpa_tag_namespace** resource creates and manages tag namespaces in Zscaler Private Access (ZPA).

        > NOTE: This an Early Access feature.

        ## Example Usage

        ```python
        import pulumi
        import zscaler_pulumi_zpa as zpa

        this = zpa.TagNamespace("this",
            name="Example Namespace",
            description="An example tag namespace",
            enabled=True)
        ```

        ## Import

        Zscaler offers a dedicated tool called Zscaler-Terraformer to allow the automated import of ZPA configurations into Terraform-compliant HashiCorp Configuration Language.
        Visit

        **zpa_tag_namespace** can be imported by using `<TAG NAMESPACE ID>` or `<TAG NAMESPACE NAME>` as the import ID.

        For example:

        ```sh
        $ pulumi import zpa:index/tagNamespace:TagNamespace example <tag_namespace_id>
        ```

        or

        ```sh
        $ pulumi import zpa:index/tagNamespace:TagNamespace example <tag_namespace_name>
        ```

        :param str resource_name: The name of the resource.
        :param TagNamespaceArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(TagNamespaceArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 microtenant_id: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 origin: Optional[pulumi.Input[_builtins.str]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = TagNamespaceArgs.__new__(TagNamespaceArgs)

            __props__.__dict__["description"] = description
            __props__.__dict__["enabled"] = enabled
            __props__.__dict__["microtenant_id"] = microtenant_id
            __props__.__dict__["name"] = name
            __props__.__dict__["origin"] = origin
            __props__.__dict__["type"] = type
        super(TagNamespace, __self__).__init__(
            'zpa:index/tagNamespace:TagNamespace',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            enabled: Optional[pulumi.Input[_builtins.bool]] = None,
            microtenant_id: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            origin: Optional[pulumi.Input[_builtins.str]] = None,
            type: Optional[pulumi.Input[_builtins.str]] = None) -> 'TagNamespace':
        """
        Get an existing TagNamespace resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: Description of the tag namespace
        :param pulumi.Input[_builtins.bool] enabled: Whether this tag namespace is enabled
        :param pulumi.Input[_builtins.str] microtenant_id: Microtenant ID
        :param pulumi.Input[_builtins.str] name: Name of the tag namespace
        :param pulumi.Input[_builtins.str] origin: Origin of the tag namespace. Defaults to CUSTOM
        :param pulumi.Input[_builtins.str] type: Type of the tag namespace. Defaults to STATIC
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _TagNamespaceState.__new__(_TagNamespaceState)

        __props__.__dict__["description"] = description
        __props__.__dict__["enabled"] = enabled
        __props__.__dict__["microtenant_id"] = microtenant_id
        __props__.__dict__["name"] = name
        __props__.__dict__["origin"] = origin
        __props__.__dict__["type"] = type
        return TagNamespace(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Description of the tag namespace
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether this tag namespace is enabled
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="microtenantId")
    def microtenant_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Microtenant ID
        """
        return pulumi.get(self, "microtenant_id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the tag namespace
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def origin(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Origin of the tag namespace. Defaults to CUSTOM
        """
        return pulumi.get(self, "origin")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Type of the tag namespace. Defaults to STATIC
        """
        return pulumi.get(self, "type")

