# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ZIACloudConfigArgs', 'ZIACloudConfig']

@pulumi.input_type
class ZIACloudConfigArgs:
    def __init__(__self__, *,
                 zia_cloud_domain: pulumi.Input[_builtins.str],
                 zia_cloud_service_api_key: pulumi.Input[_builtins.str],
                 zia_password: pulumi.Input[_builtins.str],
                 zia_sandbox_api_token: pulumi.Input[_builtins.str],
                 zia_username: pulumi.Input[_builtins.str]):
        """
        The set of arguments for constructing a ZIACloudConfig resource.
        :param pulumi.Input[_builtins.str] zia_cloud_domain: - (String) The supported ZIA cloud name. Supported values are:
        :param pulumi.Input[_builtins.str] zia_cloud_service_api_key: - (String) The ZIA Cloud service api key
        :param pulumi.Input[_builtins.str] zia_password: - (String) The ZIA admin password with permission to use the api key
        :param pulumi.Input[_builtins.str] zia_sandbox_api_token: - (String) The ZIA Sandbox API token
        :param pulumi.Input[_builtins.str] zia_username: - (String) The ZIA admin username with permission to use the api key
        """
        pulumi.set(__self__, "zia_cloud_domain", zia_cloud_domain)
        pulumi.set(__self__, "zia_cloud_service_api_key", zia_cloud_service_api_key)
        pulumi.set(__self__, "zia_password", zia_password)
        pulumi.set(__self__, "zia_sandbox_api_token", zia_sandbox_api_token)
        pulumi.set(__self__, "zia_username", zia_username)

    @_builtins.property
    @pulumi.getter(name="ziaCloudDomain")
    def zia_cloud_domain(self) -> pulumi.Input[_builtins.str]:
        """
        - (String) The supported ZIA cloud name. Supported values are:
        """
        return pulumi.get(self, "zia_cloud_domain")

    @zia_cloud_domain.setter
    def zia_cloud_domain(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "zia_cloud_domain", value)

    @_builtins.property
    @pulumi.getter(name="ziaCloudServiceApiKey")
    def zia_cloud_service_api_key(self) -> pulumi.Input[_builtins.str]:
        """
        - (String) The ZIA Cloud service api key
        """
        return pulumi.get(self, "zia_cloud_service_api_key")

    @zia_cloud_service_api_key.setter
    def zia_cloud_service_api_key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "zia_cloud_service_api_key", value)

    @_builtins.property
    @pulumi.getter(name="ziaPassword")
    def zia_password(self) -> pulumi.Input[_builtins.str]:
        """
        - (String) The ZIA admin password with permission to use the api key
        """
        return pulumi.get(self, "zia_password")

    @zia_password.setter
    def zia_password(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "zia_password", value)

    @_builtins.property
    @pulumi.getter(name="ziaSandboxApiToken")
    def zia_sandbox_api_token(self) -> pulumi.Input[_builtins.str]:
        """
        - (String) The ZIA Sandbox API token
        """
        return pulumi.get(self, "zia_sandbox_api_token")

    @zia_sandbox_api_token.setter
    def zia_sandbox_api_token(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "zia_sandbox_api_token", value)

    @_builtins.property
    @pulumi.getter(name="ziaUsername")
    def zia_username(self) -> pulumi.Input[_builtins.str]:
        """
        - (String) The ZIA admin username with permission to use the api key
        """
        return pulumi.get(self, "zia_username")

    @zia_username.setter
    def zia_username(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "zia_username", value)


@pulumi.input_type
class _ZIACloudConfigState:
    def __init__(__self__, *,
                 zia_cloud_domain: Optional[pulumi.Input[_builtins.str]] = None,
                 zia_cloud_service_api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 zia_password: Optional[pulumi.Input[_builtins.str]] = None,
                 zia_sandbox_api_token: Optional[pulumi.Input[_builtins.str]] = None,
                 zia_username: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering ZIACloudConfig resources.
        :param pulumi.Input[_builtins.str] zia_cloud_domain: - (String) The supported ZIA cloud name. Supported values are:
        :param pulumi.Input[_builtins.str] zia_cloud_service_api_key: - (String) The ZIA Cloud service api key
        :param pulumi.Input[_builtins.str] zia_password: - (String) The ZIA admin password with permission to use the api key
        :param pulumi.Input[_builtins.str] zia_sandbox_api_token: - (String) The ZIA Sandbox API token
        :param pulumi.Input[_builtins.str] zia_username: - (String) The ZIA admin username with permission to use the api key
        """
        if zia_cloud_domain is not None:
            pulumi.set(__self__, "zia_cloud_domain", zia_cloud_domain)
        if zia_cloud_service_api_key is not None:
            pulumi.set(__self__, "zia_cloud_service_api_key", zia_cloud_service_api_key)
        if zia_password is not None:
            pulumi.set(__self__, "zia_password", zia_password)
        if zia_sandbox_api_token is not None:
            pulumi.set(__self__, "zia_sandbox_api_token", zia_sandbox_api_token)
        if zia_username is not None:
            pulumi.set(__self__, "zia_username", zia_username)

    @_builtins.property
    @pulumi.getter(name="ziaCloudDomain")
    def zia_cloud_domain(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        - (String) The supported ZIA cloud name. Supported values are:
        """
        return pulumi.get(self, "zia_cloud_domain")

    @zia_cloud_domain.setter
    def zia_cloud_domain(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "zia_cloud_domain", value)

    @_builtins.property
    @pulumi.getter(name="ziaCloudServiceApiKey")
    def zia_cloud_service_api_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        - (String) The ZIA Cloud service api key
        """
        return pulumi.get(self, "zia_cloud_service_api_key")

    @zia_cloud_service_api_key.setter
    def zia_cloud_service_api_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "zia_cloud_service_api_key", value)

    @_builtins.property
    @pulumi.getter(name="ziaPassword")
    def zia_password(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        - (String) The ZIA admin password with permission to use the api key
        """
        return pulumi.get(self, "zia_password")

    @zia_password.setter
    def zia_password(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "zia_password", value)

    @_builtins.property
    @pulumi.getter(name="ziaSandboxApiToken")
    def zia_sandbox_api_token(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        - (String) The ZIA Sandbox API token
        """
        return pulumi.get(self, "zia_sandbox_api_token")

    @zia_sandbox_api_token.setter
    def zia_sandbox_api_token(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "zia_sandbox_api_token", value)

    @_builtins.property
    @pulumi.getter(name="ziaUsername")
    def zia_username(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        - (String) The ZIA admin username with permission to use the api key
        """
        return pulumi.get(self, "zia_username")

    @zia_username.setter
    def zia_username(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "zia_username", value)


@pulumi.type_token("zpa:index/zIACloudConfig:ZIACloudConfig")
class ZIACloudConfig(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 zia_cloud_domain: Optional[pulumi.Input[_builtins.str]] = None,
                 zia_cloud_service_api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 zia_password: Optional[pulumi.Input[_builtins.str]] = None,
                 zia_sandbox_api_token: Optional[pulumi.Input[_builtins.str]] = None,
                 zia_username: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        * [Official documentation](https://help.zscaler.com/zpa/about-user-portals)
        * [API documentation](https://help.zscaler.com/zpa/about-user-portals)

        The **zpa_zia_cloud_config** resource configures the Zscaler Cloud Sandbox Settings in the Zscaler Private Access cloud. This resource is required when configuring the policy type resource `PolicyAccessCapabilitiesRule`.

        ## Example Usage

        ```python
        import pulumi
        import zscaler_pulumi_zpa as zpa

        ######### PASSWORDS IN THIS FILE ARE FAKE AND NOT USED IN PRODUCTION SYSTEMS #########
        this = zpa.ZIACloudConfig("this",
            zia_username="",
            zia_password="",
            zia_cloud_service_api_key="",
            zia_sandbox_api_token="",
            zia_cloud_domain="")
        ```

        ## Import

        Zscaler offers a dedicated tool called Zscaler-Terraformer to allow the automated import of ZPA configurations into Terraform-compliant HashiCorp Configuration Language.

        Visit

        **zpa_zia_cloud_config** can be imported by using `<ZIA_CLOUD_CONFIG>` as the import ID.

        For example:

        ```sh
        $ pulumi import zpa:index/zIACloudConfig:ZIACloudConfig example <zia_cloud_config>
        ```

        or

        ```sh
        $ pulumi import zpa:index/zIACloudConfig:ZIACloudConfig example <zia_cloud_config>
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] zia_cloud_domain: - (String) The supported ZIA cloud name. Supported values are:
        :param pulumi.Input[_builtins.str] zia_cloud_service_api_key: - (String) The ZIA Cloud service api key
        :param pulumi.Input[_builtins.str] zia_password: - (String) The ZIA admin password with permission to use the api key
        :param pulumi.Input[_builtins.str] zia_sandbox_api_token: - (String) The ZIA Sandbox API token
        :param pulumi.Input[_builtins.str] zia_username: - (String) The ZIA admin username with permission to use the api key
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ZIACloudConfigArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        * [Official documentation](https://help.zscaler.com/zpa/about-user-portals)
        * [API documentation](https://help.zscaler.com/zpa/about-user-portals)

        The **zpa_zia_cloud_config** resource configures the Zscaler Cloud Sandbox Settings in the Zscaler Private Access cloud. This resource is required when configuring the policy type resource `PolicyAccessCapabilitiesRule`.

        ## Example Usage

        ```python
        import pulumi
        import zscaler_pulumi_zpa as zpa

        ######### PASSWORDS IN THIS FILE ARE FAKE AND NOT USED IN PRODUCTION SYSTEMS #########
        this = zpa.ZIACloudConfig("this",
            zia_username="",
            zia_password="",
            zia_cloud_service_api_key="",
            zia_sandbox_api_token="",
            zia_cloud_domain="")
        ```

        ## Import

        Zscaler offers a dedicated tool called Zscaler-Terraformer to allow the automated import of ZPA configurations into Terraform-compliant HashiCorp Configuration Language.

        Visit

        **zpa_zia_cloud_config** can be imported by using `<ZIA_CLOUD_CONFIG>` as the import ID.

        For example:

        ```sh
        $ pulumi import zpa:index/zIACloudConfig:ZIACloudConfig example <zia_cloud_config>
        ```

        or

        ```sh
        $ pulumi import zpa:index/zIACloudConfig:ZIACloudConfig example <zia_cloud_config>
        ```

        :param str resource_name: The name of the resource.
        :param ZIACloudConfigArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ZIACloudConfigArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 zia_cloud_domain: Optional[pulumi.Input[_builtins.str]] = None,
                 zia_cloud_service_api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 zia_password: Optional[pulumi.Input[_builtins.str]] = None,
                 zia_sandbox_api_token: Optional[pulumi.Input[_builtins.str]] = None,
                 zia_username: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ZIACloudConfigArgs.__new__(ZIACloudConfigArgs)

            if zia_cloud_domain is None and not opts.urn:
                raise TypeError("Missing required property 'zia_cloud_domain'")
            __props__.__dict__["zia_cloud_domain"] = zia_cloud_domain
            if zia_cloud_service_api_key is None and not opts.urn:
                raise TypeError("Missing required property 'zia_cloud_service_api_key'")
            __props__.__dict__["zia_cloud_service_api_key"] = None if zia_cloud_service_api_key is None else pulumi.Output.secret(zia_cloud_service_api_key)
            if zia_password is None and not opts.urn:
                raise TypeError("Missing required property 'zia_password'")
            __props__.__dict__["zia_password"] = None if zia_password is None else pulumi.Output.secret(zia_password)
            if zia_sandbox_api_token is None and not opts.urn:
                raise TypeError("Missing required property 'zia_sandbox_api_token'")
            __props__.__dict__["zia_sandbox_api_token"] = None if zia_sandbox_api_token is None else pulumi.Output.secret(zia_sandbox_api_token)
            if zia_username is None and not opts.urn:
                raise TypeError("Missing required property 'zia_username'")
            __props__.__dict__["zia_username"] = zia_username
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["ziaCloudServiceApiKey", "ziaPassword", "ziaSandboxApiToken"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(ZIACloudConfig, __self__).__init__(
            'zpa:index/zIACloudConfig:ZIACloudConfig',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            zia_cloud_domain: Optional[pulumi.Input[_builtins.str]] = None,
            zia_cloud_service_api_key: Optional[pulumi.Input[_builtins.str]] = None,
            zia_password: Optional[pulumi.Input[_builtins.str]] = None,
            zia_sandbox_api_token: Optional[pulumi.Input[_builtins.str]] = None,
            zia_username: Optional[pulumi.Input[_builtins.str]] = None) -> 'ZIACloudConfig':
        """
        Get an existing ZIACloudConfig resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] zia_cloud_domain: - (String) The supported ZIA cloud name. Supported values are:
        :param pulumi.Input[_builtins.str] zia_cloud_service_api_key: - (String) The ZIA Cloud service api key
        :param pulumi.Input[_builtins.str] zia_password: - (String) The ZIA admin password with permission to use the api key
        :param pulumi.Input[_builtins.str] zia_sandbox_api_token: - (String) The ZIA Sandbox API token
        :param pulumi.Input[_builtins.str] zia_username: - (String) The ZIA admin username with permission to use the api key
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ZIACloudConfigState.__new__(_ZIACloudConfigState)

        __props__.__dict__["zia_cloud_domain"] = zia_cloud_domain
        __props__.__dict__["zia_cloud_service_api_key"] = zia_cloud_service_api_key
        __props__.__dict__["zia_password"] = zia_password
        __props__.__dict__["zia_sandbox_api_token"] = zia_sandbox_api_token
        __props__.__dict__["zia_username"] = zia_username
        return ZIACloudConfig(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="ziaCloudDomain")
    def zia_cloud_domain(self) -> pulumi.Output[_builtins.str]:
        """
        - (String) The supported ZIA cloud name. Supported values are:
        """
        return pulumi.get(self, "zia_cloud_domain")

    @_builtins.property
    @pulumi.getter(name="ziaCloudServiceApiKey")
    def zia_cloud_service_api_key(self) -> pulumi.Output[_builtins.str]:
        """
        - (String) The ZIA Cloud service api key
        """
        return pulumi.get(self, "zia_cloud_service_api_key")

    @_builtins.property
    @pulumi.getter(name="ziaPassword")
    def zia_password(self) -> pulumi.Output[_builtins.str]:
        """
        - (String) The ZIA admin password with permission to use the api key
        """
        return pulumi.get(self, "zia_password")

    @_builtins.property
    @pulumi.getter(name="ziaSandboxApiToken")
    def zia_sandbox_api_token(self) -> pulumi.Output[_builtins.str]:
        """
        - (String) The ZIA Sandbox API token
        """
        return pulumi.get(self, "zia_sandbox_api_token")

    @_builtins.property
    @pulumi.getter(name="ziaUsername")
    def zia_username(self) -> pulumi.Output[_builtins.str]:
        """
        - (String) The ZIA admin username with permission to use the api key
        """
        return pulumi.get(self, "zia_username")

