// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zpa

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/zscaler/pulumi-zpa/sdk/go/zpa/internal"
)

// * [Official documentation](https://help.zscaler.com/zpa/adding-ip-ranges)
// * [API documentation](https://help.zscaler.com/zpa/adding-ip-ranges)
//
// The **zpa_application_segment_multimatch_bulk** resource to bulk updates application segment Multimatch in multiple applications.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/zscaler/pulumi-zpa/sdk/go/zpa"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zpa.NewApplicationSegmentMultimatchBulk(ctx, "this", &zpa.ApplicationSegmentMultimatchBulkArgs{
//				ApplicationIds: pulumi.StringArray{
//					pulumi.String("72058304855164528"),
//					pulumi.String("72058304855164536"),
//				},
//				MatchStyle: pulumi.String("EXCLUSIVE"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type ApplicationSegmentMultimatchBulk struct {
	pulumi.CustomResourceState

	// The list of Application Segment IDs
	ApplicationIds pulumi.StringArrayOutput `pulumi:"applicationIds"`
	// Indicates if Multimatch is enabled for the application segment. If enabled (INCLUSIVE), the request allows traffic to match multiple applications. If disabled (EXCLUSIVE), the request allows traffic to match a single application. A domain can only be INCLUSIVE or EXCLUSIVE, and any application segment can only contain inclusive or exclusive domains. Supported values: `EXCLUSIVE` and `INCLUSIVE`
	MatchStyle pulumi.StringOutput `pulumi:"matchStyle"`
}

// NewApplicationSegmentMultimatchBulk registers a new resource with the given unique name, arguments, and options.
func NewApplicationSegmentMultimatchBulk(ctx *pulumi.Context,
	name string, args *ApplicationSegmentMultimatchBulkArgs, opts ...pulumi.ResourceOption) (*ApplicationSegmentMultimatchBulk, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ApplicationIds == nil {
		return nil, errors.New("invalid value for required argument 'ApplicationIds'")
	}
	if args.MatchStyle == nil {
		return nil, errors.New("invalid value for required argument 'MatchStyle'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ApplicationSegmentMultimatchBulk
	err := ctx.RegisterResource("zpa:index/applicationSegmentMultimatchBulk:ApplicationSegmentMultimatchBulk", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetApplicationSegmentMultimatchBulk gets an existing ApplicationSegmentMultimatchBulk resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetApplicationSegmentMultimatchBulk(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ApplicationSegmentMultimatchBulkState, opts ...pulumi.ResourceOption) (*ApplicationSegmentMultimatchBulk, error) {
	var resource ApplicationSegmentMultimatchBulk
	err := ctx.ReadResource("zpa:index/applicationSegmentMultimatchBulk:ApplicationSegmentMultimatchBulk", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ApplicationSegmentMultimatchBulk resources.
type applicationSegmentMultimatchBulkState struct {
	// The list of Application Segment IDs
	ApplicationIds []string `pulumi:"applicationIds"`
	// Indicates if Multimatch is enabled for the application segment. If enabled (INCLUSIVE), the request allows traffic to match multiple applications. If disabled (EXCLUSIVE), the request allows traffic to match a single application. A domain can only be INCLUSIVE or EXCLUSIVE, and any application segment can only contain inclusive or exclusive domains. Supported values: `EXCLUSIVE` and `INCLUSIVE`
	MatchStyle *string `pulumi:"matchStyle"`
}

type ApplicationSegmentMultimatchBulkState struct {
	// The list of Application Segment IDs
	ApplicationIds pulumi.StringArrayInput
	// Indicates if Multimatch is enabled for the application segment. If enabled (INCLUSIVE), the request allows traffic to match multiple applications. If disabled (EXCLUSIVE), the request allows traffic to match a single application. A domain can only be INCLUSIVE or EXCLUSIVE, and any application segment can only contain inclusive or exclusive domains. Supported values: `EXCLUSIVE` and `INCLUSIVE`
	MatchStyle pulumi.StringPtrInput
}

func (ApplicationSegmentMultimatchBulkState) ElementType() reflect.Type {
	return reflect.TypeOf((*applicationSegmentMultimatchBulkState)(nil)).Elem()
}

type applicationSegmentMultimatchBulkArgs struct {
	// The list of Application Segment IDs
	ApplicationIds []string `pulumi:"applicationIds"`
	// Indicates if Multimatch is enabled for the application segment. If enabled (INCLUSIVE), the request allows traffic to match multiple applications. If disabled (EXCLUSIVE), the request allows traffic to match a single application. A domain can only be INCLUSIVE or EXCLUSIVE, and any application segment can only contain inclusive or exclusive domains. Supported values: `EXCLUSIVE` and `INCLUSIVE`
	MatchStyle string `pulumi:"matchStyle"`
}

// The set of arguments for constructing a ApplicationSegmentMultimatchBulk resource.
type ApplicationSegmentMultimatchBulkArgs struct {
	// The list of Application Segment IDs
	ApplicationIds pulumi.StringArrayInput
	// Indicates if Multimatch is enabled for the application segment. If enabled (INCLUSIVE), the request allows traffic to match multiple applications. If disabled (EXCLUSIVE), the request allows traffic to match a single application. A domain can only be INCLUSIVE or EXCLUSIVE, and any application segment can only contain inclusive or exclusive domains. Supported values: `EXCLUSIVE` and `INCLUSIVE`
	MatchStyle pulumi.StringInput
}

func (ApplicationSegmentMultimatchBulkArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*applicationSegmentMultimatchBulkArgs)(nil)).Elem()
}

type ApplicationSegmentMultimatchBulkInput interface {
	pulumi.Input

	ToApplicationSegmentMultimatchBulkOutput() ApplicationSegmentMultimatchBulkOutput
	ToApplicationSegmentMultimatchBulkOutputWithContext(ctx context.Context) ApplicationSegmentMultimatchBulkOutput
}

func (*ApplicationSegmentMultimatchBulk) ElementType() reflect.Type {
	return reflect.TypeOf((**ApplicationSegmentMultimatchBulk)(nil)).Elem()
}

func (i *ApplicationSegmentMultimatchBulk) ToApplicationSegmentMultimatchBulkOutput() ApplicationSegmentMultimatchBulkOutput {
	return i.ToApplicationSegmentMultimatchBulkOutputWithContext(context.Background())
}

func (i *ApplicationSegmentMultimatchBulk) ToApplicationSegmentMultimatchBulkOutputWithContext(ctx context.Context) ApplicationSegmentMultimatchBulkOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApplicationSegmentMultimatchBulkOutput)
}

// ApplicationSegmentMultimatchBulkArrayInput is an input type that accepts ApplicationSegmentMultimatchBulkArray and ApplicationSegmentMultimatchBulkArrayOutput values.
// You can construct a concrete instance of `ApplicationSegmentMultimatchBulkArrayInput` via:
//
//	ApplicationSegmentMultimatchBulkArray{ ApplicationSegmentMultimatchBulkArgs{...} }
type ApplicationSegmentMultimatchBulkArrayInput interface {
	pulumi.Input

	ToApplicationSegmentMultimatchBulkArrayOutput() ApplicationSegmentMultimatchBulkArrayOutput
	ToApplicationSegmentMultimatchBulkArrayOutputWithContext(context.Context) ApplicationSegmentMultimatchBulkArrayOutput
}

type ApplicationSegmentMultimatchBulkArray []ApplicationSegmentMultimatchBulkInput

func (ApplicationSegmentMultimatchBulkArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ApplicationSegmentMultimatchBulk)(nil)).Elem()
}

func (i ApplicationSegmentMultimatchBulkArray) ToApplicationSegmentMultimatchBulkArrayOutput() ApplicationSegmentMultimatchBulkArrayOutput {
	return i.ToApplicationSegmentMultimatchBulkArrayOutputWithContext(context.Background())
}

func (i ApplicationSegmentMultimatchBulkArray) ToApplicationSegmentMultimatchBulkArrayOutputWithContext(ctx context.Context) ApplicationSegmentMultimatchBulkArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApplicationSegmentMultimatchBulkArrayOutput)
}

// ApplicationSegmentMultimatchBulkMapInput is an input type that accepts ApplicationSegmentMultimatchBulkMap and ApplicationSegmentMultimatchBulkMapOutput values.
// You can construct a concrete instance of `ApplicationSegmentMultimatchBulkMapInput` via:
//
//	ApplicationSegmentMultimatchBulkMap{ "key": ApplicationSegmentMultimatchBulkArgs{...} }
type ApplicationSegmentMultimatchBulkMapInput interface {
	pulumi.Input

	ToApplicationSegmentMultimatchBulkMapOutput() ApplicationSegmentMultimatchBulkMapOutput
	ToApplicationSegmentMultimatchBulkMapOutputWithContext(context.Context) ApplicationSegmentMultimatchBulkMapOutput
}

type ApplicationSegmentMultimatchBulkMap map[string]ApplicationSegmentMultimatchBulkInput

func (ApplicationSegmentMultimatchBulkMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ApplicationSegmentMultimatchBulk)(nil)).Elem()
}

func (i ApplicationSegmentMultimatchBulkMap) ToApplicationSegmentMultimatchBulkMapOutput() ApplicationSegmentMultimatchBulkMapOutput {
	return i.ToApplicationSegmentMultimatchBulkMapOutputWithContext(context.Background())
}

func (i ApplicationSegmentMultimatchBulkMap) ToApplicationSegmentMultimatchBulkMapOutputWithContext(ctx context.Context) ApplicationSegmentMultimatchBulkMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApplicationSegmentMultimatchBulkMapOutput)
}

type ApplicationSegmentMultimatchBulkOutput struct{ *pulumi.OutputState }

func (ApplicationSegmentMultimatchBulkOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ApplicationSegmentMultimatchBulk)(nil)).Elem()
}

func (o ApplicationSegmentMultimatchBulkOutput) ToApplicationSegmentMultimatchBulkOutput() ApplicationSegmentMultimatchBulkOutput {
	return o
}

func (o ApplicationSegmentMultimatchBulkOutput) ToApplicationSegmentMultimatchBulkOutputWithContext(ctx context.Context) ApplicationSegmentMultimatchBulkOutput {
	return o
}

// The list of Application Segment IDs
func (o ApplicationSegmentMultimatchBulkOutput) ApplicationIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ApplicationSegmentMultimatchBulk) pulumi.StringArrayOutput { return v.ApplicationIds }).(pulumi.StringArrayOutput)
}

// Indicates if Multimatch is enabled for the application segment. If enabled (INCLUSIVE), the request allows traffic to match multiple applications. If disabled (EXCLUSIVE), the request allows traffic to match a single application. A domain can only be INCLUSIVE or EXCLUSIVE, and any application segment can only contain inclusive or exclusive domains. Supported values: `EXCLUSIVE` and `INCLUSIVE`
func (o ApplicationSegmentMultimatchBulkOutput) MatchStyle() pulumi.StringOutput {
	return o.ApplyT(func(v *ApplicationSegmentMultimatchBulk) pulumi.StringOutput { return v.MatchStyle }).(pulumi.StringOutput)
}

type ApplicationSegmentMultimatchBulkArrayOutput struct{ *pulumi.OutputState }

func (ApplicationSegmentMultimatchBulkArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ApplicationSegmentMultimatchBulk)(nil)).Elem()
}

func (o ApplicationSegmentMultimatchBulkArrayOutput) ToApplicationSegmentMultimatchBulkArrayOutput() ApplicationSegmentMultimatchBulkArrayOutput {
	return o
}

func (o ApplicationSegmentMultimatchBulkArrayOutput) ToApplicationSegmentMultimatchBulkArrayOutputWithContext(ctx context.Context) ApplicationSegmentMultimatchBulkArrayOutput {
	return o
}

func (o ApplicationSegmentMultimatchBulkArrayOutput) Index(i pulumi.IntInput) ApplicationSegmentMultimatchBulkOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ApplicationSegmentMultimatchBulk {
		return vs[0].([]*ApplicationSegmentMultimatchBulk)[vs[1].(int)]
	}).(ApplicationSegmentMultimatchBulkOutput)
}

type ApplicationSegmentMultimatchBulkMapOutput struct{ *pulumi.OutputState }

func (ApplicationSegmentMultimatchBulkMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ApplicationSegmentMultimatchBulk)(nil)).Elem()
}

func (o ApplicationSegmentMultimatchBulkMapOutput) ToApplicationSegmentMultimatchBulkMapOutput() ApplicationSegmentMultimatchBulkMapOutput {
	return o
}

func (o ApplicationSegmentMultimatchBulkMapOutput) ToApplicationSegmentMultimatchBulkMapOutputWithContext(ctx context.Context) ApplicationSegmentMultimatchBulkMapOutput {
	return o
}

func (o ApplicationSegmentMultimatchBulkMapOutput) MapIndex(k pulumi.StringInput) ApplicationSegmentMultimatchBulkOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ApplicationSegmentMultimatchBulk {
		return vs[0].(map[string]*ApplicationSegmentMultimatchBulk)[vs[1].(string)]
	}).(ApplicationSegmentMultimatchBulkOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ApplicationSegmentMultimatchBulkInput)(nil)).Elem(), &ApplicationSegmentMultimatchBulk{})
	pulumi.RegisterInputType(reflect.TypeOf((*ApplicationSegmentMultimatchBulkArrayInput)(nil)).Elem(), ApplicationSegmentMultimatchBulkArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ApplicationSegmentMultimatchBulkMapInput)(nil)).Elem(), ApplicationSegmentMultimatchBulkMap{})
	pulumi.RegisterOutputType(ApplicationSegmentMultimatchBulkOutput{})
	pulumi.RegisterOutputType(ApplicationSegmentMultimatchBulkArrayOutput{})
	pulumi.RegisterOutputType(ApplicationSegmentMultimatchBulkMapOutput{})
}
