// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zpa

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/zscaler/pulumi-zpa/sdk/go/zpa/internal"
)

// Use the **zpa_application_segment_weightedlb_config** resource to create, update, or delete the weighted load balancer configuration for an application segment in the Zscaler Private Access cloud.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/zscaler/pulumi-zpa/sdk/go/zpa"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zpa.NewApplicationSegmentWeightedlbConfig(ctx, "this", &zpa.ApplicationSegmentWeightedlbConfigArgs{
//				ApplicationName:       pulumi.String("app02"),
//				WeightedLoadBalancing: pulumi.Bool(true),
//				ApplicationToServerGroupMappings: zpa.ApplicationSegmentWeightedlbConfigApplicationToServerGroupMappingArray{
//					&zpa.ApplicationSegmentWeightedlbConfigApplicationToServerGroupMappingArgs{
//						Name:   pulumi.String("Example100"),
//						Weight: pulumi.String("100"),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type ApplicationSegmentWeightedlbConfig struct {
	pulumi.CustomResourceState

	// Application segment identifier to manage. Either applicationId or applicationName must be provided.
	ApplicationId pulumi.StringOutput `pulumi:"applicationId"`
	// Application segment name to manage. Either applicationId or applicationName must be provided.
	ApplicationName pulumi.StringOutput `pulumi:"applicationName"`
	// Application to server group mapping details and weights.
	ApplicationToServerGroupMappings ApplicationSegmentWeightedlbConfigApplicationToServerGroupMappingArrayOutput `pulumi:"applicationToServerGroupMappings"`
	// Optional microtenant identifier.
	MicrotenantId pulumi.StringPtrOutput `pulumi:"microtenantId"`
	// Enable or disable weighted load balancing for the application segment.
	WeightedLoadBalancing pulumi.BoolOutput `pulumi:"weightedLoadBalancing"`
}

// NewApplicationSegmentWeightedlbConfig registers a new resource with the given unique name, arguments, and options.
func NewApplicationSegmentWeightedlbConfig(ctx *pulumi.Context,
	name string, args *ApplicationSegmentWeightedlbConfigArgs, opts ...pulumi.ResourceOption) (*ApplicationSegmentWeightedlbConfig, error) {
	if args == nil {
		args = &ApplicationSegmentWeightedlbConfigArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ApplicationSegmentWeightedlbConfig
	err := ctx.RegisterResource("zpa:index/applicationSegmentWeightedlbConfig:ApplicationSegmentWeightedlbConfig", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetApplicationSegmentWeightedlbConfig gets an existing ApplicationSegmentWeightedlbConfig resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetApplicationSegmentWeightedlbConfig(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ApplicationSegmentWeightedlbConfigState, opts ...pulumi.ResourceOption) (*ApplicationSegmentWeightedlbConfig, error) {
	var resource ApplicationSegmentWeightedlbConfig
	err := ctx.ReadResource("zpa:index/applicationSegmentWeightedlbConfig:ApplicationSegmentWeightedlbConfig", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ApplicationSegmentWeightedlbConfig resources.
type applicationSegmentWeightedlbConfigState struct {
	// Application segment identifier to manage. Either applicationId or applicationName must be provided.
	ApplicationId *string `pulumi:"applicationId"`
	// Application segment name to manage. Either applicationId or applicationName must be provided.
	ApplicationName *string `pulumi:"applicationName"`
	// Application to server group mapping details and weights.
	ApplicationToServerGroupMappings []ApplicationSegmentWeightedlbConfigApplicationToServerGroupMapping `pulumi:"applicationToServerGroupMappings"`
	// Optional microtenant identifier.
	MicrotenantId *string `pulumi:"microtenantId"`
	// Enable or disable weighted load balancing for the application segment.
	WeightedLoadBalancing *bool `pulumi:"weightedLoadBalancing"`
}

type ApplicationSegmentWeightedlbConfigState struct {
	// Application segment identifier to manage. Either applicationId or applicationName must be provided.
	ApplicationId pulumi.StringPtrInput
	// Application segment name to manage. Either applicationId or applicationName must be provided.
	ApplicationName pulumi.StringPtrInput
	// Application to server group mapping details and weights.
	ApplicationToServerGroupMappings ApplicationSegmentWeightedlbConfigApplicationToServerGroupMappingArrayInput
	// Optional microtenant identifier.
	MicrotenantId pulumi.StringPtrInput
	// Enable or disable weighted load balancing for the application segment.
	WeightedLoadBalancing pulumi.BoolPtrInput
}

func (ApplicationSegmentWeightedlbConfigState) ElementType() reflect.Type {
	return reflect.TypeOf((*applicationSegmentWeightedlbConfigState)(nil)).Elem()
}

type applicationSegmentWeightedlbConfigArgs struct {
	// Application segment identifier to manage. Either applicationId or applicationName must be provided.
	ApplicationId *string `pulumi:"applicationId"`
	// Application segment name to manage. Either applicationId or applicationName must be provided.
	ApplicationName *string `pulumi:"applicationName"`
	// Application to server group mapping details and weights.
	ApplicationToServerGroupMappings []ApplicationSegmentWeightedlbConfigApplicationToServerGroupMapping `pulumi:"applicationToServerGroupMappings"`
	// Optional microtenant identifier.
	MicrotenantId *string `pulumi:"microtenantId"`
	// Enable or disable weighted load balancing for the application segment.
	WeightedLoadBalancing *bool `pulumi:"weightedLoadBalancing"`
}

// The set of arguments for constructing a ApplicationSegmentWeightedlbConfig resource.
type ApplicationSegmentWeightedlbConfigArgs struct {
	// Application segment identifier to manage. Either applicationId or applicationName must be provided.
	ApplicationId pulumi.StringPtrInput
	// Application segment name to manage. Either applicationId or applicationName must be provided.
	ApplicationName pulumi.StringPtrInput
	// Application to server group mapping details and weights.
	ApplicationToServerGroupMappings ApplicationSegmentWeightedlbConfigApplicationToServerGroupMappingArrayInput
	// Optional microtenant identifier.
	MicrotenantId pulumi.StringPtrInput
	// Enable or disable weighted load balancing for the application segment.
	WeightedLoadBalancing pulumi.BoolPtrInput
}

func (ApplicationSegmentWeightedlbConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*applicationSegmentWeightedlbConfigArgs)(nil)).Elem()
}

type ApplicationSegmentWeightedlbConfigInput interface {
	pulumi.Input

	ToApplicationSegmentWeightedlbConfigOutput() ApplicationSegmentWeightedlbConfigOutput
	ToApplicationSegmentWeightedlbConfigOutputWithContext(ctx context.Context) ApplicationSegmentWeightedlbConfigOutput
}

func (*ApplicationSegmentWeightedlbConfig) ElementType() reflect.Type {
	return reflect.TypeOf((**ApplicationSegmentWeightedlbConfig)(nil)).Elem()
}

func (i *ApplicationSegmentWeightedlbConfig) ToApplicationSegmentWeightedlbConfigOutput() ApplicationSegmentWeightedlbConfigOutput {
	return i.ToApplicationSegmentWeightedlbConfigOutputWithContext(context.Background())
}

func (i *ApplicationSegmentWeightedlbConfig) ToApplicationSegmentWeightedlbConfigOutputWithContext(ctx context.Context) ApplicationSegmentWeightedlbConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApplicationSegmentWeightedlbConfigOutput)
}

// ApplicationSegmentWeightedlbConfigArrayInput is an input type that accepts ApplicationSegmentWeightedlbConfigArray and ApplicationSegmentWeightedlbConfigArrayOutput values.
// You can construct a concrete instance of `ApplicationSegmentWeightedlbConfigArrayInput` via:
//
//	ApplicationSegmentWeightedlbConfigArray{ ApplicationSegmentWeightedlbConfigArgs{...} }
type ApplicationSegmentWeightedlbConfigArrayInput interface {
	pulumi.Input

	ToApplicationSegmentWeightedlbConfigArrayOutput() ApplicationSegmentWeightedlbConfigArrayOutput
	ToApplicationSegmentWeightedlbConfigArrayOutputWithContext(context.Context) ApplicationSegmentWeightedlbConfigArrayOutput
}

type ApplicationSegmentWeightedlbConfigArray []ApplicationSegmentWeightedlbConfigInput

func (ApplicationSegmentWeightedlbConfigArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ApplicationSegmentWeightedlbConfig)(nil)).Elem()
}

func (i ApplicationSegmentWeightedlbConfigArray) ToApplicationSegmentWeightedlbConfigArrayOutput() ApplicationSegmentWeightedlbConfigArrayOutput {
	return i.ToApplicationSegmentWeightedlbConfigArrayOutputWithContext(context.Background())
}

func (i ApplicationSegmentWeightedlbConfigArray) ToApplicationSegmentWeightedlbConfigArrayOutputWithContext(ctx context.Context) ApplicationSegmentWeightedlbConfigArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApplicationSegmentWeightedlbConfigArrayOutput)
}

// ApplicationSegmentWeightedlbConfigMapInput is an input type that accepts ApplicationSegmentWeightedlbConfigMap and ApplicationSegmentWeightedlbConfigMapOutput values.
// You can construct a concrete instance of `ApplicationSegmentWeightedlbConfigMapInput` via:
//
//	ApplicationSegmentWeightedlbConfigMap{ "key": ApplicationSegmentWeightedlbConfigArgs{...} }
type ApplicationSegmentWeightedlbConfigMapInput interface {
	pulumi.Input

	ToApplicationSegmentWeightedlbConfigMapOutput() ApplicationSegmentWeightedlbConfigMapOutput
	ToApplicationSegmentWeightedlbConfigMapOutputWithContext(context.Context) ApplicationSegmentWeightedlbConfigMapOutput
}

type ApplicationSegmentWeightedlbConfigMap map[string]ApplicationSegmentWeightedlbConfigInput

func (ApplicationSegmentWeightedlbConfigMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ApplicationSegmentWeightedlbConfig)(nil)).Elem()
}

func (i ApplicationSegmentWeightedlbConfigMap) ToApplicationSegmentWeightedlbConfigMapOutput() ApplicationSegmentWeightedlbConfigMapOutput {
	return i.ToApplicationSegmentWeightedlbConfigMapOutputWithContext(context.Background())
}

func (i ApplicationSegmentWeightedlbConfigMap) ToApplicationSegmentWeightedlbConfigMapOutputWithContext(ctx context.Context) ApplicationSegmentWeightedlbConfigMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApplicationSegmentWeightedlbConfigMapOutput)
}

type ApplicationSegmentWeightedlbConfigOutput struct{ *pulumi.OutputState }

func (ApplicationSegmentWeightedlbConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ApplicationSegmentWeightedlbConfig)(nil)).Elem()
}

func (o ApplicationSegmentWeightedlbConfigOutput) ToApplicationSegmentWeightedlbConfigOutput() ApplicationSegmentWeightedlbConfigOutput {
	return o
}

func (o ApplicationSegmentWeightedlbConfigOutput) ToApplicationSegmentWeightedlbConfigOutputWithContext(ctx context.Context) ApplicationSegmentWeightedlbConfigOutput {
	return o
}

// Application segment identifier to manage. Either applicationId or applicationName must be provided.
func (o ApplicationSegmentWeightedlbConfigOutput) ApplicationId() pulumi.StringOutput {
	return o.ApplyT(func(v *ApplicationSegmentWeightedlbConfig) pulumi.StringOutput { return v.ApplicationId }).(pulumi.StringOutput)
}

// Application segment name to manage. Either applicationId or applicationName must be provided.
func (o ApplicationSegmentWeightedlbConfigOutput) ApplicationName() pulumi.StringOutput {
	return o.ApplyT(func(v *ApplicationSegmentWeightedlbConfig) pulumi.StringOutput { return v.ApplicationName }).(pulumi.StringOutput)
}

// Application to server group mapping details and weights.
func (o ApplicationSegmentWeightedlbConfigOutput) ApplicationToServerGroupMappings() ApplicationSegmentWeightedlbConfigApplicationToServerGroupMappingArrayOutput {
	return o.ApplyT(func(v *ApplicationSegmentWeightedlbConfig) ApplicationSegmentWeightedlbConfigApplicationToServerGroupMappingArrayOutput {
		return v.ApplicationToServerGroupMappings
	}).(ApplicationSegmentWeightedlbConfigApplicationToServerGroupMappingArrayOutput)
}

// Optional microtenant identifier.
func (o ApplicationSegmentWeightedlbConfigOutput) MicrotenantId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ApplicationSegmentWeightedlbConfig) pulumi.StringPtrOutput { return v.MicrotenantId }).(pulumi.StringPtrOutput)
}

// Enable or disable weighted load balancing for the application segment.
func (o ApplicationSegmentWeightedlbConfigOutput) WeightedLoadBalancing() pulumi.BoolOutput {
	return o.ApplyT(func(v *ApplicationSegmentWeightedlbConfig) pulumi.BoolOutput { return v.WeightedLoadBalancing }).(pulumi.BoolOutput)
}

type ApplicationSegmentWeightedlbConfigArrayOutput struct{ *pulumi.OutputState }

func (ApplicationSegmentWeightedlbConfigArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ApplicationSegmentWeightedlbConfig)(nil)).Elem()
}

func (o ApplicationSegmentWeightedlbConfigArrayOutput) ToApplicationSegmentWeightedlbConfigArrayOutput() ApplicationSegmentWeightedlbConfigArrayOutput {
	return o
}

func (o ApplicationSegmentWeightedlbConfigArrayOutput) ToApplicationSegmentWeightedlbConfigArrayOutputWithContext(ctx context.Context) ApplicationSegmentWeightedlbConfigArrayOutput {
	return o
}

func (o ApplicationSegmentWeightedlbConfigArrayOutput) Index(i pulumi.IntInput) ApplicationSegmentWeightedlbConfigOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ApplicationSegmentWeightedlbConfig {
		return vs[0].([]*ApplicationSegmentWeightedlbConfig)[vs[1].(int)]
	}).(ApplicationSegmentWeightedlbConfigOutput)
}

type ApplicationSegmentWeightedlbConfigMapOutput struct{ *pulumi.OutputState }

func (ApplicationSegmentWeightedlbConfigMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ApplicationSegmentWeightedlbConfig)(nil)).Elem()
}

func (o ApplicationSegmentWeightedlbConfigMapOutput) ToApplicationSegmentWeightedlbConfigMapOutput() ApplicationSegmentWeightedlbConfigMapOutput {
	return o
}

func (o ApplicationSegmentWeightedlbConfigMapOutput) ToApplicationSegmentWeightedlbConfigMapOutputWithContext(ctx context.Context) ApplicationSegmentWeightedlbConfigMapOutput {
	return o
}

func (o ApplicationSegmentWeightedlbConfigMapOutput) MapIndex(k pulumi.StringInput) ApplicationSegmentWeightedlbConfigOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ApplicationSegmentWeightedlbConfig {
		return vs[0].(map[string]*ApplicationSegmentWeightedlbConfig)[vs[1].(string)]
	}).(ApplicationSegmentWeightedlbConfigOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ApplicationSegmentWeightedlbConfigInput)(nil)).Elem(), &ApplicationSegmentWeightedlbConfig{})
	pulumi.RegisterInputType(reflect.TypeOf((*ApplicationSegmentWeightedlbConfigArrayInput)(nil)).Elem(), ApplicationSegmentWeightedlbConfigArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ApplicationSegmentWeightedlbConfigMapInput)(nil)).Elem(), ApplicationSegmentWeightedlbConfigMap{})
	pulumi.RegisterOutputType(ApplicationSegmentWeightedlbConfigOutput{})
	pulumi.RegisterOutputType(ApplicationSegmentWeightedlbConfigArrayOutput{})
	pulumi.RegisterOutputType(ApplicationSegmentWeightedlbConfigMapOutput{})
}
