// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zpa

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/zscaler/pulumi-zpa/sdk/go/zpa/internal"
)

// * [Official documentation](https://help.zscaler.com/zpa/about-redirection-policy)
// * [API documentation](https://help.zscaler.com/zpa/configuring-redirection-policies-using-api)
//
// The **zpa_policy_redirection_rule** resource creates a policy redirection access rule in the Zscaler Private Access cloud.
//
//	⚠️ **WARNING:**: The attribute ``ruleOrder`` is now deprecated in favor of the new resource  ``policyAccessRuleReorder``
//
// ## Example Usage
//
// ## Import
//
// Zscaler offers a dedicated tool called Zscaler-Terraformer to allow the automated import of ZPA configurations into Terraform-compliant HashiCorp Configuration Language.
//
// # Visit
//
// Policy Access Isolation Rule can be imported by using `<POLICY REDIRECTION RULE ID>` as the import ID.
//
// For example:
//
// ```sh
// $ pulumi import zpa:index/policyAccessRedirectionRule:PolicyAccessRedirectionRule example <rule_id>
// ```
type PolicyAccessRedirectionRule struct {
	pulumi.CustomResourceState

	// This is for providing the rule action.
	Action pulumi.StringPtrOutput `pulumi:"action"`
	// This field defines the description of the server.
	ActionId          pulumi.StringPtrOutput `pulumi:"actionId"`
	BypassDefaultRule pulumi.BoolPtrOutput   `pulumi:"bypassDefaultRule"`
	// This is for proviidng the set of conditions for the policy.
	Conditions PolicyAccessRedirectionRuleConditionArrayOutput `pulumi:"conditions"`
	// This is for providing a customer message for the user.
	CustomMsg pulumi.StringOutput `pulumi:"customMsg"`
	// This is for providing a customer message for the user.
	DefaultRule pulumi.BoolPtrOutput `pulumi:"defaultRule"`
	// This is the description of the access policy.
	Description    pulumi.StringPtrOutput `pulumi:"description"`
	LssDefaultRule pulumi.BoolPtrOutput   `pulumi:"lssDefaultRule"`
	MicrotenantId  pulumi.StringOutput    `pulumi:"microtenantId"`
	// This is the name of the policy.
	Name              pulumi.StringOutput    `pulumi:"name"`
	Operator          pulumi.StringOutput    `pulumi:"operator"`
	PolicySetId       pulumi.StringOutput    `pulumi:"policySetId"`
	PolicyType        pulumi.StringOutput    `pulumi:"policyType"`
	Priority          pulumi.StringOutput    `pulumi:"priority"`
	ReauthDefaultRule pulumi.BoolPtrOutput   `pulumi:"reauthDefaultRule"`
	ReauthIdleTimeout pulumi.StringPtrOutput `pulumi:"reauthIdleTimeout"`
	ReauthTimeout     pulumi.StringPtrOutput `pulumi:"reauthTimeout"`
	// Deprecated: The `ruleOrder` field is now deprecated for all zpa access policy resources in favor of the resource `PolicyAccessReorderRule`
	RuleOrder pulumi.StringOutput `pulumi:"ruleOrder"`
	// List of the service edge group IDs.
	ServiceEdgeGroups      PolicyAccessRedirectionRuleServiceEdgeGroupArrayOutput `pulumi:"serviceEdgeGroups"`
	ZpnCbiProfileId        pulumi.StringOutput                                    `pulumi:"zpnCbiProfileId"`
	ZpnInspectionProfileId pulumi.StringOutput                                    `pulumi:"zpnInspectionProfileId"`
	ZpnIsolationProfileId  pulumi.StringOutput                                    `pulumi:"zpnIsolationProfileId"`
}

// NewPolicyAccessRedirectionRule registers a new resource with the given unique name, arguments, and options.
func NewPolicyAccessRedirectionRule(ctx *pulumi.Context,
	name string, args *PolicyAccessRedirectionRuleArgs, opts ...pulumi.ResourceOption) (*PolicyAccessRedirectionRule, error) {
	if args == nil {
		args = &PolicyAccessRedirectionRuleArgs{}
	}

	aliases := pulumi.Aliases([]pulumi.Alias{
		{
			Type: pulumi.String("zpa:index/policyRedirectionRule:PolicyRedirectionRule"),
		},
	})
	opts = append(opts, aliases)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource PolicyAccessRedirectionRule
	err := ctx.RegisterResource("zpa:index/policyAccessRedirectionRule:PolicyAccessRedirectionRule", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPolicyAccessRedirectionRule gets an existing PolicyAccessRedirectionRule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPolicyAccessRedirectionRule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PolicyAccessRedirectionRuleState, opts ...pulumi.ResourceOption) (*PolicyAccessRedirectionRule, error) {
	var resource PolicyAccessRedirectionRule
	err := ctx.ReadResource("zpa:index/policyAccessRedirectionRule:PolicyAccessRedirectionRule", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PolicyAccessRedirectionRule resources.
type policyAccessRedirectionRuleState struct {
	// This is for providing the rule action.
	Action *string `pulumi:"action"`
	// This field defines the description of the server.
	ActionId          *string `pulumi:"actionId"`
	BypassDefaultRule *bool   `pulumi:"bypassDefaultRule"`
	// This is for proviidng the set of conditions for the policy.
	Conditions []PolicyAccessRedirectionRuleCondition `pulumi:"conditions"`
	// This is for providing a customer message for the user.
	CustomMsg *string `pulumi:"customMsg"`
	// This is for providing a customer message for the user.
	DefaultRule *bool `pulumi:"defaultRule"`
	// This is the description of the access policy.
	Description    *string `pulumi:"description"`
	LssDefaultRule *bool   `pulumi:"lssDefaultRule"`
	MicrotenantId  *string `pulumi:"microtenantId"`
	// This is the name of the policy.
	Name              *string `pulumi:"name"`
	Operator          *string `pulumi:"operator"`
	PolicySetId       *string `pulumi:"policySetId"`
	PolicyType        *string `pulumi:"policyType"`
	Priority          *string `pulumi:"priority"`
	ReauthDefaultRule *bool   `pulumi:"reauthDefaultRule"`
	ReauthIdleTimeout *string `pulumi:"reauthIdleTimeout"`
	ReauthTimeout     *string `pulumi:"reauthTimeout"`
	// Deprecated: The `ruleOrder` field is now deprecated for all zpa access policy resources in favor of the resource `PolicyAccessReorderRule`
	RuleOrder *string `pulumi:"ruleOrder"`
	// List of the service edge group IDs.
	ServiceEdgeGroups      []PolicyAccessRedirectionRuleServiceEdgeGroup `pulumi:"serviceEdgeGroups"`
	ZpnCbiProfileId        *string                                       `pulumi:"zpnCbiProfileId"`
	ZpnInspectionProfileId *string                                       `pulumi:"zpnInspectionProfileId"`
	ZpnIsolationProfileId  *string                                       `pulumi:"zpnIsolationProfileId"`
}

type PolicyAccessRedirectionRuleState struct {
	// This is for providing the rule action.
	Action pulumi.StringPtrInput
	// This field defines the description of the server.
	ActionId          pulumi.StringPtrInput
	BypassDefaultRule pulumi.BoolPtrInput
	// This is for proviidng the set of conditions for the policy.
	Conditions PolicyAccessRedirectionRuleConditionArrayInput
	// This is for providing a customer message for the user.
	CustomMsg pulumi.StringPtrInput
	// This is for providing a customer message for the user.
	DefaultRule pulumi.BoolPtrInput
	// This is the description of the access policy.
	Description    pulumi.StringPtrInput
	LssDefaultRule pulumi.BoolPtrInput
	MicrotenantId  pulumi.StringPtrInput
	// This is the name of the policy.
	Name              pulumi.StringPtrInput
	Operator          pulumi.StringPtrInput
	PolicySetId       pulumi.StringPtrInput
	PolicyType        pulumi.StringPtrInput
	Priority          pulumi.StringPtrInput
	ReauthDefaultRule pulumi.BoolPtrInput
	ReauthIdleTimeout pulumi.StringPtrInput
	ReauthTimeout     pulumi.StringPtrInput
	// Deprecated: The `ruleOrder` field is now deprecated for all zpa access policy resources in favor of the resource `PolicyAccessReorderRule`
	RuleOrder pulumi.StringPtrInput
	// List of the service edge group IDs.
	ServiceEdgeGroups      PolicyAccessRedirectionRuleServiceEdgeGroupArrayInput
	ZpnCbiProfileId        pulumi.StringPtrInput
	ZpnInspectionProfileId pulumi.StringPtrInput
	ZpnIsolationProfileId  pulumi.StringPtrInput
}

func (PolicyAccessRedirectionRuleState) ElementType() reflect.Type {
	return reflect.TypeOf((*policyAccessRedirectionRuleState)(nil)).Elem()
}

type policyAccessRedirectionRuleArgs struct {
	// This is for providing the rule action.
	Action *string `pulumi:"action"`
	// This field defines the description of the server.
	ActionId          *string `pulumi:"actionId"`
	BypassDefaultRule *bool   `pulumi:"bypassDefaultRule"`
	// This is for proviidng the set of conditions for the policy.
	Conditions []PolicyAccessRedirectionRuleCondition `pulumi:"conditions"`
	// This is for providing a customer message for the user.
	CustomMsg *string `pulumi:"customMsg"`
	// This is for providing a customer message for the user.
	DefaultRule *bool `pulumi:"defaultRule"`
	// This is the description of the access policy.
	Description    *string `pulumi:"description"`
	LssDefaultRule *bool   `pulumi:"lssDefaultRule"`
	MicrotenantId  *string `pulumi:"microtenantId"`
	// This is the name of the policy.
	Name              *string `pulumi:"name"`
	Operator          *string `pulumi:"operator"`
	PolicySetId       *string `pulumi:"policySetId"`
	PolicyType        *string `pulumi:"policyType"`
	Priority          *string `pulumi:"priority"`
	ReauthDefaultRule *bool   `pulumi:"reauthDefaultRule"`
	ReauthIdleTimeout *string `pulumi:"reauthIdleTimeout"`
	ReauthTimeout     *string `pulumi:"reauthTimeout"`
	// Deprecated: The `ruleOrder` field is now deprecated for all zpa access policy resources in favor of the resource `PolicyAccessReorderRule`
	RuleOrder *string `pulumi:"ruleOrder"`
	// List of the service edge group IDs.
	ServiceEdgeGroups      []PolicyAccessRedirectionRuleServiceEdgeGroup `pulumi:"serviceEdgeGroups"`
	ZpnCbiProfileId        *string                                       `pulumi:"zpnCbiProfileId"`
	ZpnInspectionProfileId *string                                       `pulumi:"zpnInspectionProfileId"`
	ZpnIsolationProfileId  *string                                       `pulumi:"zpnIsolationProfileId"`
}

// The set of arguments for constructing a PolicyAccessRedirectionRule resource.
type PolicyAccessRedirectionRuleArgs struct {
	// This is for providing the rule action.
	Action pulumi.StringPtrInput
	// This field defines the description of the server.
	ActionId          pulumi.StringPtrInput
	BypassDefaultRule pulumi.BoolPtrInput
	// This is for proviidng the set of conditions for the policy.
	Conditions PolicyAccessRedirectionRuleConditionArrayInput
	// This is for providing a customer message for the user.
	CustomMsg pulumi.StringPtrInput
	// This is for providing a customer message for the user.
	DefaultRule pulumi.BoolPtrInput
	// This is the description of the access policy.
	Description    pulumi.StringPtrInput
	LssDefaultRule pulumi.BoolPtrInput
	MicrotenantId  pulumi.StringPtrInput
	// This is the name of the policy.
	Name              pulumi.StringPtrInput
	Operator          pulumi.StringPtrInput
	PolicySetId       pulumi.StringPtrInput
	PolicyType        pulumi.StringPtrInput
	Priority          pulumi.StringPtrInput
	ReauthDefaultRule pulumi.BoolPtrInput
	ReauthIdleTimeout pulumi.StringPtrInput
	ReauthTimeout     pulumi.StringPtrInput
	// Deprecated: The `ruleOrder` field is now deprecated for all zpa access policy resources in favor of the resource `PolicyAccessReorderRule`
	RuleOrder pulumi.StringPtrInput
	// List of the service edge group IDs.
	ServiceEdgeGroups      PolicyAccessRedirectionRuleServiceEdgeGroupArrayInput
	ZpnCbiProfileId        pulumi.StringPtrInput
	ZpnInspectionProfileId pulumi.StringPtrInput
	ZpnIsolationProfileId  pulumi.StringPtrInput
}

func (PolicyAccessRedirectionRuleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*policyAccessRedirectionRuleArgs)(nil)).Elem()
}

type PolicyAccessRedirectionRuleInput interface {
	pulumi.Input

	ToPolicyAccessRedirectionRuleOutput() PolicyAccessRedirectionRuleOutput
	ToPolicyAccessRedirectionRuleOutputWithContext(ctx context.Context) PolicyAccessRedirectionRuleOutput
}

func (*PolicyAccessRedirectionRule) ElementType() reflect.Type {
	return reflect.TypeOf((**PolicyAccessRedirectionRule)(nil)).Elem()
}

func (i *PolicyAccessRedirectionRule) ToPolicyAccessRedirectionRuleOutput() PolicyAccessRedirectionRuleOutput {
	return i.ToPolicyAccessRedirectionRuleOutputWithContext(context.Background())
}

func (i *PolicyAccessRedirectionRule) ToPolicyAccessRedirectionRuleOutputWithContext(ctx context.Context) PolicyAccessRedirectionRuleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PolicyAccessRedirectionRuleOutput)
}

// PolicyAccessRedirectionRuleArrayInput is an input type that accepts PolicyAccessRedirectionRuleArray and PolicyAccessRedirectionRuleArrayOutput values.
// You can construct a concrete instance of `PolicyAccessRedirectionRuleArrayInput` via:
//
//	PolicyAccessRedirectionRuleArray{ PolicyAccessRedirectionRuleArgs{...} }
type PolicyAccessRedirectionRuleArrayInput interface {
	pulumi.Input

	ToPolicyAccessRedirectionRuleArrayOutput() PolicyAccessRedirectionRuleArrayOutput
	ToPolicyAccessRedirectionRuleArrayOutputWithContext(context.Context) PolicyAccessRedirectionRuleArrayOutput
}

type PolicyAccessRedirectionRuleArray []PolicyAccessRedirectionRuleInput

func (PolicyAccessRedirectionRuleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PolicyAccessRedirectionRule)(nil)).Elem()
}

func (i PolicyAccessRedirectionRuleArray) ToPolicyAccessRedirectionRuleArrayOutput() PolicyAccessRedirectionRuleArrayOutput {
	return i.ToPolicyAccessRedirectionRuleArrayOutputWithContext(context.Background())
}

func (i PolicyAccessRedirectionRuleArray) ToPolicyAccessRedirectionRuleArrayOutputWithContext(ctx context.Context) PolicyAccessRedirectionRuleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PolicyAccessRedirectionRuleArrayOutput)
}

// PolicyAccessRedirectionRuleMapInput is an input type that accepts PolicyAccessRedirectionRuleMap and PolicyAccessRedirectionRuleMapOutput values.
// You can construct a concrete instance of `PolicyAccessRedirectionRuleMapInput` via:
//
//	PolicyAccessRedirectionRuleMap{ "key": PolicyAccessRedirectionRuleArgs{...} }
type PolicyAccessRedirectionRuleMapInput interface {
	pulumi.Input

	ToPolicyAccessRedirectionRuleMapOutput() PolicyAccessRedirectionRuleMapOutput
	ToPolicyAccessRedirectionRuleMapOutputWithContext(context.Context) PolicyAccessRedirectionRuleMapOutput
}

type PolicyAccessRedirectionRuleMap map[string]PolicyAccessRedirectionRuleInput

func (PolicyAccessRedirectionRuleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PolicyAccessRedirectionRule)(nil)).Elem()
}

func (i PolicyAccessRedirectionRuleMap) ToPolicyAccessRedirectionRuleMapOutput() PolicyAccessRedirectionRuleMapOutput {
	return i.ToPolicyAccessRedirectionRuleMapOutputWithContext(context.Background())
}

func (i PolicyAccessRedirectionRuleMap) ToPolicyAccessRedirectionRuleMapOutputWithContext(ctx context.Context) PolicyAccessRedirectionRuleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PolicyAccessRedirectionRuleMapOutput)
}

type PolicyAccessRedirectionRuleOutput struct{ *pulumi.OutputState }

func (PolicyAccessRedirectionRuleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PolicyAccessRedirectionRule)(nil)).Elem()
}

func (o PolicyAccessRedirectionRuleOutput) ToPolicyAccessRedirectionRuleOutput() PolicyAccessRedirectionRuleOutput {
	return o
}

func (o PolicyAccessRedirectionRuleOutput) ToPolicyAccessRedirectionRuleOutputWithContext(ctx context.Context) PolicyAccessRedirectionRuleOutput {
	return o
}

// This is for providing the rule action.
func (o PolicyAccessRedirectionRuleOutput) Action() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PolicyAccessRedirectionRule) pulumi.StringPtrOutput { return v.Action }).(pulumi.StringPtrOutput)
}

// This field defines the description of the server.
func (o PolicyAccessRedirectionRuleOutput) ActionId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PolicyAccessRedirectionRule) pulumi.StringPtrOutput { return v.ActionId }).(pulumi.StringPtrOutput)
}

func (o PolicyAccessRedirectionRuleOutput) BypassDefaultRule() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *PolicyAccessRedirectionRule) pulumi.BoolPtrOutput { return v.BypassDefaultRule }).(pulumi.BoolPtrOutput)
}

// This is for proviidng the set of conditions for the policy.
func (o PolicyAccessRedirectionRuleOutput) Conditions() PolicyAccessRedirectionRuleConditionArrayOutput {
	return o.ApplyT(func(v *PolicyAccessRedirectionRule) PolicyAccessRedirectionRuleConditionArrayOutput {
		return v.Conditions
	}).(PolicyAccessRedirectionRuleConditionArrayOutput)
}

// This is for providing a customer message for the user.
func (o PolicyAccessRedirectionRuleOutput) CustomMsg() pulumi.StringOutput {
	return o.ApplyT(func(v *PolicyAccessRedirectionRule) pulumi.StringOutput { return v.CustomMsg }).(pulumi.StringOutput)
}

// This is for providing a customer message for the user.
func (o PolicyAccessRedirectionRuleOutput) DefaultRule() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *PolicyAccessRedirectionRule) pulumi.BoolPtrOutput { return v.DefaultRule }).(pulumi.BoolPtrOutput)
}

// This is the description of the access policy.
func (o PolicyAccessRedirectionRuleOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PolicyAccessRedirectionRule) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

func (o PolicyAccessRedirectionRuleOutput) LssDefaultRule() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *PolicyAccessRedirectionRule) pulumi.BoolPtrOutput { return v.LssDefaultRule }).(pulumi.BoolPtrOutput)
}

func (o PolicyAccessRedirectionRuleOutput) MicrotenantId() pulumi.StringOutput {
	return o.ApplyT(func(v *PolicyAccessRedirectionRule) pulumi.StringOutput { return v.MicrotenantId }).(pulumi.StringOutput)
}

// This is the name of the policy.
func (o PolicyAccessRedirectionRuleOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *PolicyAccessRedirectionRule) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o PolicyAccessRedirectionRuleOutput) Operator() pulumi.StringOutput {
	return o.ApplyT(func(v *PolicyAccessRedirectionRule) pulumi.StringOutput { return v.Operator }).(pulumi.StringOutput)
}

func (o PolicyAccessRedirectionRuleOutput) PolicySetId() pulumi.StringOutput {
	return o.ApplyT(func(v *PolicyAccessRedirectionRule) pulumi.StringOutput { return v.PolicySetId }).(pulumi.StringOutput)
}

func (o PolicyAccessRedirectionRuleOutput) PolicyType() pulumi.StringOutput {
	return o.ApplyT(func(v *PolicyAccessRedirectionRule) pulumi.StringOutput { return v.PolicyType }).(pulumi.StringOutput)
}

func (o PolicyAccessRedirectionRuleOutput) Priority() pulumi.StringOutput {
	return o.ApplyT(func(v *PolicyAccessRedirectionRule) pulumi.StringOutput { return v.Priority }).(pulumi.StringOutput)
}

func (o PolicyAccessRedirectionRuleOutput) ReauthDefaultRule() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *PolicyAccessRedirectionRule) pulumi.BoolPtrOutput { return v.ReauthDefaultRule }).(pulumi.BoolPtrOutput)
}

func (o PolicyAccessRedirectionRuleOutput) ReauthIdleTimeout() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PolicyAccessRedirectionRule) pulumi.StringPtrOutput { return v.ReauthIdleTimeout }).(pulumi.StringPtrOutput)
}

func (o PolicyAccessRedirectionRuleOutput) ReauthTimeout() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PolicyAccessRedirectionRule) pulumi.StringPtrOutput { return v.ReauthTimeout }).(pulumi.StringPtrOutput)
}

// Deprecated: The `ruleOrder` field is now deprecated for all zpa access policy resources in favor of the resource `PolicyAccessReorderRule`
func (o PolicyAccessRedirectionRuleOutput) RuleOrder() pulumi.StringOutput {
	return o.ApplyT(func(v *PolicyAccessRedirectionRule) pulumi.StringOutput { return v.RuleOrder }).(pulumi.StringOutput)
}

// List of the service edge group IDs.
func (o PolicyAccessRedirectionRuleOutput) ServiceEdgeGroups() PolicyAccessRedirectionRuleServiceEdgeGroupArrayOutput {
	return o.ApplyT(func(v *PolicyAccessRedirectionRule) PolicyAccessRedirectionRuleServiceEdgeGroupArrayOutput {
		return v.ServiceEdgeGroups
	}).(PolicyAccessRedirectionRuleServiceEdgeGroupArrayOutput)
}

func (o PolicyAccessRedirectionRuleOutput) ZpnCbiProfileId() pulumi.StringOutput {
	return o.ApplyT(func(v *PolicyAccessRedirectionRule) pulumi.StringOutput { return v.ZpnCbiProfileId }).(pulumi.StringOutput)
}

func (o PolicyAccessRedirectionRuleOutput) ZpnInspectionProfileId() pulumi.StringOutput {
	return o.ApplyT(func(v *PolicyAccessRedirectionRule) pulumi.StringOutput { return v.ZpnInspectionProfileId }).(pulumi.StringOutput)
}

func (o PolicyAccessRedirectionRuleOutput) ZpnIsolationProfileId() pulumi.StringOutput {
	return o.ApplyT(func(v *PolicyAccessRedirectionRule) pulumi.StringOutput { return v.ZpnIsolationProfileId }).(pulumi.StringOutput)
}

type PolicyAccessRedirectionRuleArrayOutput struct{ *pulumi.OutputState }

func (PolicyAccessRedirectionRuleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PolicyAccessRedirectionRule)(nil)).Elem()
}

func (o PolicyAccessRedirectionRuleArrayOutput) ToPolicyAccessRedirectionRuleArrayOutput() PolicyAccessRedirectionRuleArrayOutput {
	return o
}

func (o PolicyAccessRedirectionRuleArrayOutput) ToPolicyAccessRedirectionRuleArrayOutputWithContext(ctx context.Context) PolicyAccessRedirectionRuleArrayOutput {
	return o
}

func (o PolicyAccessRedirectionRuleArrayOutput) Index(i pulumi.IntInput) PolicyAccessRedirectionRuleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *PolicyAccessRedirectionRule {
		return vs[0].([]*PolicyAccessRedirectionRule)[vs[1].(int)]
	}).(PolicyAccessRedirectionRuleOutput)
}

type PolicyAccessRedirectionRuleMapOutput struct{ *pulumi.OutputState }

func (PolicyAccessRedirectionRuleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PolicyAccessRedirectionRule)(nil)).Elem()
}

func (o PolicyAccessRedirectionRuleMapOutput) ToPolicyAccessRedirectionRuleMapOutput() PolicyAccessRedirectionRuleMapOutput {
	return o
}

func (o PolicyAccessRedirectionRuleMapOutput) ToPolicyAccessRedirectionRuleMapOutputWithContext(ctx context.Context) PolicyAccessRedirectionRuleMapOutput {
	return o
}

func (o PolicyAccessRedirectionRuleMapOutput) MapIndex(k pulumi.StringInput) PolicyAccessRedirectionRuleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *PolicyAccessRedirectionRule {
		return vs[0].(map[string]*PolicyAccessRedirectionRule)[vs[1].(string)]
	}).(PolicyAccessRedirectionRuleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PolicyAccessRedirectionRuleInput)(nil)).Elem(), &PolicyAccessRedirectionRule{})
	pulumi.RegisterInputType(reflect.TypeOf((*PolicyAccessRedirectionRuleArrayInput)(nil)).Elem(), PolicyAccessRedirectionRuleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*PolicyAccessRedirectionRuleMapInput)(nil)).Elem(), PolicyAccessRedirectionRuleMap{})
	pulumi.RegisterOutputType(PolicyAccessRedirectionRuleOutput{})
	pulumi.RegisterOutputType(PolicyAccessRedirectionRuleArrayOutput{})
	pulumi.RegisterOutputType(PolicyAccessRedirectionRuleMapOutput{})
}
