// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zpa

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/zscaler/pulumi-zpa/sdk/go/zpa/internal"
)

// The **zpa_tag_key** resource creates and manages tag keys within a tag namespace in Zscaler Private Access (ZPA).
//
// > NOTE: This an Early Access feature.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/zscaler/pulumi-zpa/sdk/go/zpa"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			this, err := zpa.NewTagNamespace(ctx, "this", &zpa.TagNamespaceArgs{
//				Name:        pulumi.String("Example Namespace"),
//				Description: pulumi.String("An example tag namespace"),
//				Enabled:     pulumi.Bool(true),
//			})
//			if err != nil {
//				return err
//			}
//			_, err = zpa.NewTagKey(ctx, "this", &zpa.TagKeyArgs{
//				Name:        pulumi.String("Environment"),
//				Description: pulumi.String("Environment tag key"),
//				Enabled:     pulumi.Bool(true),
//				NamespaceId: this.ID(),
//				TagValues: zpa.TagKeyTagValueArray{
//					&zpa.TagKeyTagValueArgs{
//						Name: pulumi.String("Production"),
//					},
//					&zpa.TagKeyTagValueArgs{
//						Name: pulumi.String("Staging"),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// Zscaler offers a dedicated tool called Zscaler-Terraformer to allow the automated import of ZPA configurations into Terraform-compliant HashiCorp Configuration Language.
// Visit
//
// **zpa_tag_key** can be imported by using the composite format `<NAMESPACE ID>/<TAG KEY ID>` or `<NAMESPACE ID>/<TAG KEY NAME>` as the import ID.
//
// For example:
//
// ```sh
// $ pulumi import zpa:index/tagKey:TagKey example <namespace_id>/<tag_key_id>
// ```
//
// or
//
// ```sh
// $ pulumi import zpa:index/tagKey:TagKey example <namespace_id>/<tag_key_name>
// ```
type TagKey struct {
	pulumi.CustomResourceState

	// Description of the tag key
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Whether this tag key is enabled
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// Microtenant ID
	MicrotenantId pulumi.StringPtrOutput `pulumi:"microtenantId"`
	// The name of the tag value.
	Name pulumi.StringOutput `pulumi:"name"`
	// ID of the tag namespace this key belongs to
	NamespaceId pulumi.StringOutput `pulumi:"namespaceId"`
	// Origin of the tag key. Defaults to CUSTOM
	Origin pulumi.StringPtrOutput `pulumi:"origin"`
	// The list of tag values. Each element contains:
	TagValues TagKeyTagValueArrayOutput `pulumi:"tagValues"`
	// Type of the tag key. Defaults to STATIC
	Type pulumi.StringPtrOutput `pulumi:"type"`
}

// NewTagKey registers a new resource with the given unique name, arguments, and options.
func NewTagKey(ctx *pulumi.Context,
	name string, args *TagKeyArgs, opts ...pulumi.ResourceOption) (*TagKey, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.NamespaceId == nil {
		return nil, errors.New("invalid value for required argument 'NamespaceId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource TagKey
	err := ctx.RegisterResource("zpa:index/tagKey:TagKey", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTagKey gets an existing TagKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTagKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TagKeyState, opts ...pulumi.ResourceOption) (*TagKey, error) {
	var resource TagKey
	err := ctx.ReadResource("zpa:index/tagKey:TagKey", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering TagKey resources.
type tagKeyState struct {
	// Description of the tag key
	Description *string `pulumi:"description"`
	// Whether this tag key is enabled
	Enabled *bool `pulumi:"enabled"`
	// Microtenant ID
	MicrotenantId *string `pulumi:"microtenantId"`
	// The name of the tag value.
	Name *string `pulumi:"name"`
	// ID of the tag namespace this key belongs to
	NamespaceId *string `pulumi:"namespaceId"`
	// Origin of the tag key. Defaults to CUSTOM
	Origin *string `pulumi:"origin"`
	// The list of tag values. Each element contains:
	TagValues []TagKeyTagValue `pulumi:"tagValues"`
	// Type of the tag key. Defaults to STATIC
	Type *string `pulumi:"type"`
}

type TagKeyState struct {
	// Description of the tag key
	Description pulumi.StringPtrInput
	// Whether this tag key is enabled
	Enabled pulumi.BoolPtrInput
	// Microtenant ID
	MicrotenantId pulumi.StringPtrInput
	// The name of the tag value.
	Name pulumi.StringPtrInput
	// ID of the tag namespace this key belongs to
	NamespaceId pulumi.StringPtrInput
	// Origin of the tag key. Defaults to CUSTOM
	Origin pulumi.StringPtrInput
	// The list of tag values. Each element contains:
	TagValues TagKeyTagValueArrayInput
	// Type of the tag key. Defaults to STATIC
	Type pulumi.StringPtrInput
}

func (TagKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*tagKeyState)(nil)).Elem()
}

type tagKeyArgs struct {
	// Description of the tag key
	Description *string `pulumi:"description"`
	// Whether this tag key is enabled
	Enabled *bool `pulumi:"enabled"`
	// Microtenant ID
	MicrotenantId *string `pulumi:"microtenantId"`
	// The name of the tag value.
	Name *string `pulumi:"name"`
	// ID of the tag namespace this key belongs to
	NamespaceId string `pulumi:"namespaceId"`
	// Origin of the tag key. Defaults to CUSTOM
	Origin *string `pulumi:"origin"`
	// The list of tag values. Each element contains:
	TagValues []TagKeyTagValue `pulumi:"tagValues"`
	// Type of the tag key. Defaults to STATIC
	Type *string `pulumi:"type"`
}

// The set of arguments for constructing a TagKey resource.
type TagKeyArgs struct {
	// Description of the tag key
	Description pulumi.StringPtrInput
	// Whether this tag key is enabled
	Enabled pulumi.BoolPtrInput
	// Microtenant ID
	MicrotenantId pulumi.StringPtrInput
	// The name of the tag value.
	Name pulumi.StringPtrInput
	// ID of the tag namespace this key belongs to
	NamespaceId pulumi.StringInput
	// Origin of the tag key. Defaults to CUSTOM
	Origin pulumi.StringPtrInput
	// The list of tag values. Each element contains:
	TagValues TagKeyTagValueArrayInput
	// Type of the tag key. Defaults to STATIC
	Type pulumi.StringPtrInput
}

func (TagKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*tagKeyArgs)(nil)).Elem()
}

type TagKeyInput interface {
	pulumi.Input

	ToTagKeyOutput() TagKeyOutput
	ToTagKeyOutputWithContext(ctx context.Context) TagKeyOutput
}

func (*TagKey) ElementType() reflect.Type {
	return reflect.TypeOf((**TagKey)(nil)).Elem()
}

func (i *TagKey) ToTagKeyOutput() TagKeyOutput {
	return i.ToTagKeyOutputWithContext(context.Background())
}

func (i *TagKey) ToTagKeyOutputWithContext(ctx context.Context) TagKeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TagKeyOutput)
}

// TagKeyArrayInput is an input type that accepts TagKeyArray and TagKeyArrayOutput values.
// You can construct a concrete instance of `TagKeyArrayInput` via:
//
//	TagKeyArray{ TagKeyArgs{...} }
type TagKeyArrayInput interface {
	pulumi.Input

	ToTagKeyArrayOutput() TagKeyArrayOutput
	ToTagKeyArrayOutputWithContext(context.Context) TagKeyArrayOutput
}

type TagKeyArray []TagKeyInput

func (TagKeyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*TagKey)(nil)).Elem()
}

func (i TagKeyArray) ToTagKeyArrayOutput() TagKeyArrayOutput {
	return i.ToTagKeyArrayOutputWithContext(context.Background())
}

func (i TagKeyArray) ToTagKeyArrayOutputWithContext(ctx context.Context) TagKeyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TagKeyArrayOutput)
}

// TagKeyMapInput is an input type that accepts TagKeyMap and TagKeyMapOutput values.
// You can construct a concrete instance of `TagKeyMapInput` via:
//
//	TagKeyMap{ "key": TagKeyArgs{...} }
type TagKeyMapInput interface {
	pulumi.Input

	ToTagKeyMapOutput() TagKeyMapOutput
	ToTagKeyMapOutputWithContext(context.Context) TagKeyMapOutput
}

type TagKeyMap map[string]TagKeyInput

func (TagKeyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*TagKey)(nil)).Elem()
}

func (i TagKeyMap) ToTagKeyMapOutput() TagKeyMapOutput {
	return i.ToTagKeyMapOutputWithContext(context.Background())
}

func (i TagKeyMap) ToTagKeyMapOutputWithContext(ctx context.Context) TagKeyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TagKeyMapOutput)
}

type TagKeyOutput struct{ *pulumi.OutputState }

func (TagKeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TagKey)(nil)).Elem()
}

func (o TagKeyOutput) ToTagKeyOutput() TagKeyOutput {
	return o
}

func (o TagKeyOutput) ToTagKeyOutputWithContext(ctx context.Context) TagKeyOutput {
	return o
}

// Description of the tag key
func (o TagKeyOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TagKey) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Whether this tag key is enabled
func (o TagKeyOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *TagKey) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// Microtenant ID
func (o TagKeyOutput) MicrotenantId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TagKey) pulumi.StringPtrOutput { return v.MicrotenantId }).(pulumi.StringPtrOutput)
}

// The name of the tag value.
func (o TagKeyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *TagKey) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// ID of the tag namespace this key belongs to
func (o TagKeyOutput) NamespaceId() pulumi.StringOutput {
	return o.ApplyT(func(v *TagKey) pulumi.StringOutput { return v.NamespaceId }).(pulumi.StringOutput)
}

// Origin of the tag key. Defaults to CUSTOM
func (o TagKeyOutput) Origin() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TagKey) pulumi.StringPtrOutput { return v.Origin }).(pulumi.StringPtrOutput)
}

// The list of tag values. Each element contains:
func (o TagKeyOutput) TagValues() TagKeyTagValueArrayOutput {
	return o.ApplyT(func(v *TagKey) TagKeyTagValueArrayOutput { return v.TagValues }).(TagKeyTagValueArrayOutput)
}

// Type of the tag key. Defaults to STATIC
func (o TagKeyOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TagKey) pulumi.StringPtrOutput { return v.Type }).(pulumi.StringPtrOutput)
}

type TagKeyArrayOutput struct{ *pulumi.OutputState }

func (TagKeyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*TagKey)(nil)).Elem()
}

func (o TagKeyArrayOutput) ToTagKeyArrayOutput() TagKeyArrayOutput {
	return o
}

func (o TagKeyArrayOutput) ToTagKeyArrayOutputWithContext(ctx context.Context) TagKeyArrayOutput {
	return o
}

func (o TagKeyArrayOutput) Index(i pulumi.IntInput) TagKeyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *TagKey {
		return vs[0].([]*TagKey)[vs[1].(int)]
	}).(TagKeyOutput)
}

type TagKeyMapOutput struct{ *pulumi.OutputState }

func (TagKeyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*TagKey)(nil)).Elem()
}

func (o TagKeyMapOutput) ToTagKeyMapOutput() TagKeyMapOutput {
	return o
}

func (o TagKeyMapOutput) ToTagKeyMapOutputWithContext(ctx context.Context) TagKeyMapOutput {
	return o
}

func (o TagKeyMapOutput) MapIndex(k pulumi.StringInput) TagKeyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *TagKey {
		return vs[0].(map[string]*TagKey)[vs[1].(string)]
	}).(TagKeyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TagKeyInput)(nil)).Elem(), &TagKey{})
	pulumi.RegisterInputType(reflect.TypeOf((*TagKeyArrayInput)(nil)).Elem(), TagKeyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*TagKeyMapInput)(nil)).Elem(), TagKeyMap{})
	pulumi.RegisterOutputType(TagKeyOutput{})
	pulumi.RegisterOutputType(TagKeyArrayOutput{})
	pulumi.RegisterOutputType(TagKeyMapOutput{})
}
