// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zpa

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/zscaler/pulumi-zpa/sdk/go/zpa/internal"
)

// * [Official documentation](https://help.zscaler.com/zpa/about-user-portals)
// * [API documentation](https://help.zscaler.com/zpa/about-user-portals)
//
// The **zpa_zia_cloud_config** resource configures the Zscaler Cloud Sandbox Settings in the Zscaler Private Access cloud. This resource is required when configuring the policy type resource `PolicyAccessCapabilitiesRule`.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/zscaler/pulumi-zpa/sdk/go/zpa"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// ######## PASSWORDS IN THIS FILE ARE FAKE AND NOT USED IN PRODUCTION SYSTEMS #########
//			_, err := zpa.NewZiaCloudConfig(ctx, "this", &zpa.ZiaCloudConfigArgs{
//				ZiaUsername:           pulumi.String(""),
//				ZiaPassword:           pulumi.String(""),
//				ZiaCloudServiceApiKey: pulumi.String(""),
//				ZiaSandboxApiToken:    pulumi.String(""),
//				ZiaCloudDomain:        pulumi.String(""),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// Zscaler offers a dedicated tool called Zscaler-Terraformer to allow the automated import of ZPA configurations into Terraform-compliant HashiCorp Configuration Language.
//
// # Visit
//
// **zpa_zia_cloud_config** can be imported by using `<ZIA_CLOUD_CONFIG>` as the import ID.
//
// For example:
//
// ```sh
// $ pulumi import zpa:index/ziaCloudConfig:ZiaCloudConfig example <zia_cloud_config>
// ```
//
// or
//
// ```sh
// $ pulumi import zpa:index/ziaCloudConfig:ZiaCloudConfig example <zia_cloud_config>
// ```
type ZiaCloudConfig struct {
	pulumi.CustomResourceState

	// - (String) The supported ZIA cloud name. Supported values are:
	ZiaCloudDomain pulumi.StringOutput `pulumi:"ziaCloudDomain"`
	// - (String) The ZIA Cloud service api key
	ZiaCloudServiceApiKey pulumi.StringOutput `pulumi:"ziaCloudServiceApiKey"`
	// - (String) The ZIA admin password with permission to use the api key
	ZiaPassword pulumi.StringOutput `pulumi:"ziaPassword"`
	// - (String) The ZIA Sandbox API token
	ZiaSandboxApiToken pulumi.StringOutput `pulumi:"ziaSandboxApiToken"`
	// - (String) The ZIA admin username with permission to use the api key
	ZiaUsername pulumi.StringOutput `pulumi:"ziaUsername"`
}

// NewZiaCloudConfig registers a new resource with the given unique name, arguments, and options.
func NewZiaCloudConfig(ctx *pulumi.Context,
	name string, args *ZiaCloudConfigArgs, opts ...pulumi.ResourceOption) (*ZiaCloudConfig, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ZiaCloudDomain == nil {
		return nil, errors.New("invalid value for required argument 'ZiaCloudDomain'")
	}
	if args.ZiaCloudServiceApiKey == nil {
		return nil, errors.New("invalid value for required argument 'ZiaCloudServiceApiKey'")
	}
	if args.ZiaPassword == nil {
		return nil, errors.New("invalid value for required argument 'ZiaPassword'")
	}
	if args.ZiaSandboxApiToken == nil {
		return nil, errors.New("invalid value for required argument 'ZiaSandboxApiToken'")
	}
	if args.ZiaUsername == nil {
		return nil, errors.New("invalid value for required argument 'ZiaUsername'")
	}
	if args.ZiaCloudServiceApiKey != nil {
		args.ZiaCloudServiceApiKey = pulumi.ToSecret(args.ZiaCloudServiceApiKey).(pulumi.StringInput)
	}
	if args.ZiaPassword != nil {
		args.ZiaPassword = pulumi.ToSecret(args.ZiaPassword).(pulumi.StringInput)
	}
	if args.ZiaSandboxApiToken != nil {
		args.ZiaSandboxApiToken = pulumi.ToSecret(args.ZiaSandboxApiToken).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"ziaCloudServiceApiKey",
		"ziaPassword",
		"ziaSandboxApiToken",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ZiaCloudConfig
	err := ctx.RegisterResource("zpa:index/ziaCloudConfig:ZiaCloudConfig", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetZiaCloudConfig gets an existing ZiaCloudConfig resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetZiaCloudConfig(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ZiaCloudConfigState, opts ...pulumi.ResourceOption) (*ZiaCloudConfig, error) {
	var resource ZiaCloudConfig
	err := ctx.ReadResource("zpa:index/ziaCloudConfig:ZiaCloudConfig", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ZiaCloudConfig resources.
type ziaCloudConfigState struct {
	// - (String) The supported ZIA cloud name. Supported values are:
	ZiaCloudDomain *string `pulumi:"ziaCloudDomain"`
	// - (String) The ZIA Cloud service api key
	ZiaCloudServiceApiKey *string `pulumi:"ziaCloudServiceApiKey"`
	// - (String) The ZIA admin password with permission to use the api key
	ZiaPassword *string `pulumi:"ziaPassword"`
	// - (String) The ZIA Sandbox API token
	ZiaSandboxApiToken *string `pulumi:"ziaSandboxApiToken"`
	// - (String) The ZIA admin username with permission to use the api key
	ZiaUsername *string `pulumi:"ziaUsername"`
}

type ZiaCloudConfigState struct {
	// - (String) The supported ZIA cloud name. Supported values are:
	ZiaCloudDomain pulumi.StringPtrInput
	// - (String) The ZIA Cloud service api key
	ZiaCloudServiceApiKey pulumi.StringPtrInput
	// - (String) The ZIA admin password with permission to use the api key
	ZiaPassword pulumi.StringPtrInput
	// - (String) The ZIA Sandbox API token
	ZiaSandboxApiToken pulumi.StringPtrInput
	// - (String) The ZIA admin username with permission to use the api key
	ZiaUsername pulumi.StringPtrInput
}

func (ZiaCloudConfigState) ElementType() reflect.Type {
	return reflect.TypeOf((*ziaCloudConfigState)(nil)).Elem()
}

type ziaCloudConfigArgs struct {
	// - (String) The supported ZIA cloud name. Supported values are:
	ZiaCloudDomain string `pulumi:"ziaCloudDomain"`
	// - (String) The ZIA Cloud service api key
	ZiaCloudServiceApiKey string `pulumi:"ziaCloudServiceApiKey"`
	// - (String) The ZIA admin password with permission to use the api key
	ZiaPassword string `pulumi:"ziaPassword"`
	// - (String) The ZIA Sandbox API token
	ZiaSandboxApiToken string `pulumi:"ziaSandboxApiToken"`
	// - (String) The ZIA admin username with permission to use the api key
	ZiaUsername string `pulumi:"ziaUsername"`
}

// The set of arguments for constructing a ZiaCloudConfig resource.
type ZiaCloudConfigArgs struct {
	// - (String) The supported ZIA cloud name. Supported values are:
	ZiaCloudDomain pulumi.StringInput
	// - (String) The ZIA Cloud service api key
	ZiaCloudServiceApiKey pulumi.StringInput
	// - (String) The ZIA admin password with permission to use the api key
	ZiaPassword pulumi.StringInput
	// - (String) The ZIA Sandbox API token
	ZiaSandboxApiToken pulumi.StringInput
	// - (String) The ZIA admin username with permission to use the api key
	ZiaUsername pulumi.StringInput
}

func (ZiaCloudConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ziaCloudConfigArgs)(nil)).Elem()
}

type ZiaCloudConfigInput interface {
	pulumi.Input

	ToZiaCloudConfigOutput() ZiaCloudConfigOutput
	ToZiaCloudConfigOutputWithContext(ctx context.Context) ZiaCloudConfigOutput
}

func (*ZiaCloudConfig) ElementType() reflect.Type {
	return reflect.TypeOf((**ZiaCloudConfig)(nil)).Elem()
}

func (i *ZiaCloudConfig) ToZiaCloudConfigOutput() ZiaCloudConfigOutput {
	return i.ToZiaCloudConfigOutputWithContext(context.Background())
}

func (i *ZiaCloudConfig) ToZiaCloudConfigOutputWithContext(ctx context.Context) ZiaCloudConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ZiaCloudConfigOutput)
}

// ZiaCloudConfigArrayInput is an input type that accepts ZiaCloudConfigArray and ZiaCloudConfigArrayOutput values.
// You can construct a concrete instance of `ZiaCloudConfigArrayInput` via:
//
//	ZiaCloudConfigArray{ ZiaCloudConfigArgs{...} }
type ZiaCloudConfigArrayInput interface {
	pulumi.Input

	ToZiaCloudConfigArrayOutput() ZiaCloudConfigArrayOutput
	ToZiaCloudConfigArrayOutputWithContext(context.Context) ZiaCloudConfigArrayOutput
}

type ZiaCloudConfigArray []ZiaCloudConfigInput

func (ZiaCloudConfigArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ZiaCloudConfig)(nil)).Elem()
}

func (i ZiaCloudConfigArray) ToZiaCloudConfigArrayOutput() ZiaCloudConfigArrayOutput {
	return i.ToZiaCloudConfigArrayOutputWithContext(context.Background())
}

func (i ZiaCloudConfigArray) ToZiaCloudConfigArrayOutputWithContext(ctx context.Context) ZiaCloudConfigArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ZiaCloudConfigArrayOutput)
}

// ZiaCloudConfigMapInput is an input type that accepts ZiaCloudConfigMap and ZiaCloudConfigMapOutput values.
// You can construct a concrete instance of `ZiaCloudConfigMapInput` via:
//
//	ZiaCloudConfigMap{ "key": ZiaCloudConfigArgs{...} }
type ZiaCloudConfigMapInput interface {
	pulumi.Input

	ToZiaCloudConfigMapOutput() ZiaCloudConfigMapOutput
	ToZiaCloudConfigMapOutputWithContext(context.Context) ZiaCloudConfigMapOutput
}

type ZiaCloudConfigMap map[string]ZiaCloudConfigInput

func (ZiaCloudConfigMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ZiaCloudConfig)(nil)).Elem()
}

func (i ZiaCloudConfigMap) ToZiaCloudConfigMapOutput() ZiaCloudConfigMapOutput {
	return i.ToZiaCloudConfigMapOutputWithContext(context.Background())
}

func (i ZiaCloudConfigMap) ToZiaCloudConfigMapOutputWithContext(ctx context.Context) ZiaCloudConfigMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ZiaCloudConfigMapOutput)
}

type ZiaCloudConfigOutput struct{ *pulumi.OutputState }

func (ZiaCloudConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ZiaCloudConfig)(nil)).Elem()
}

func (o ZiaCloudConfigOutput) ToZiaCloudConfigOutput() ZiaCloudConfigOutput {
	return o
}

func (o ZiaCloudConfigOutput) ToZiaCloudConfigOutputWithContext(ctx context.Context) ZiaCloudConfigOutput {
	return o
}

// - (String) The supported ZIA cloud name. Supported values are:
func (o ZiaCloudConfigOutput) ZiaCloudDomain() pulumi.StringOutput {
	return o.ApplyT(func(v *ZiaCloudConfig) pulumi.StringOutput { return v.ZiaCloudDomain }).(pulumi.StringOutput)
}

// - (String) The ZIA Cloud service api key
func (o ZiaCloudConfigOutput) ZiaCloudServiceApiKey() pulumi.StringOutput {
	return o.ApplyT(func(v *ZiaCloudConfig) pulumi.StringOutput { return v.ZiaCloudServiceApiKey }).(pulumi.StringOutput)
}

// - (String) The ZIA admin password with permission to use the api key
func (o ZiaCloudConfigOutput) ZiaPassword() pulumi.StringOutput {
	return o.ApplyT(func(v *ZiaCloudConfig) pulumi.StringOutput { return v.ZiaPassword }).(pulumi.StringOutput)
}

// - (String) The ZIA Sandbox API token
func (o ZiaCloudConfigOutput) ZiaSandboxApiToken() pulumi.StringOutput {
	return o.ApplyT(func(v *ZiaCloudConfig) pulumi.StringOutput { return v.ZiaSandboxApiToken }).(pulumi.StringOutput)
}

// - (String) The ZIA admin username with permission to use the api key
func (o ZiaCloudConfigOutput) ZiaUsername() pulumi.StringOutput {
	return o.ApplyT(func(v *ZiaCloudConfig) pulumi.StringOutput { return v.ZiaUsername }).(pulumi.StringOutput)
}

type ZiaCloudConfigArrayOutput struct{ *pulumi.OutputState }

func (ZiaCloudConfigArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ZiaCloudConfig)(nil)).Elem()
}

func (o ZiaCloudConfigArrayOutput) ToZiaCloudConfigArrayOutput() ZiaCloudConfigArrayOutput {
	return o
}

func (o ZiaCloudConfigArrayOutput) ToZiaCloudConfigArrayOutputWithContext(ctx context.Context) ZiaCloudConfigArrayOutput {
	return o
}

func (o ZiaCloudConfigArrayOutput) Index(i pulumi.IntInput) ZiaCloudConfigOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ZiaCloudConfig {
		return vs[0].([]*ZiaCloudConfig)[vs[1].(int)]
	}).(ZiaCloudConfigOutput)
}

type ZiaCloudConfigMapOutput struct{ *pulumi.OutputState }

func (ZiaCloudConfigMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ZiaCloudConfig)(nil)).Elem()
}

func (o ZiaCloudConfigMapOutput) ToZiaCloudConfigMapOutput() ZiaCloudConfigMapOutput {
	return o
}

func (o ZiaCloudConfigMapOutput) ToZiaCloudConfigMapOutputWithContext(ctx context.Context) ZiaCloudConfigMapOutput {
	return o
}

func (o ZiaCloudConfigMapOutput) MapIndex(k pulumi.StringInput) ZiaCloudConfigOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ZiaCloudConfig {
		return vs[0].(map[string]*ZiaCloudConfig)[vs[1].(string)]
	}).(ZiaCloudConfigOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ZiaCloudConfigInput)(nil)).Elem(), &ZiaCloudConfig{})
	pulumi.RegisterInputType(reflect.TypeOf((*ZiaCloudConfigArrayInput)(nil)).Elem(), ZiaCloudConfigArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ZiaCloudConfigMapInput)(nil)).Elem(), ZiaCloudConfigMap{})
	pulumi.RegisterOutputType(ZiaCloudConfigOutput{})
	pulumi.RegisterOutputType(ZiaCloudConfigArrayOutput{})
	pulumi.RegisterOutputType(ZiaCloudConfigMapOutput{})
}
