// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace zscaler.PulumiPackage.Zpa
{
    public static class GetServerGroup
    {
        /// <summary>
        /// * [Official documentation](https://help.zscaler.com/zpa/about-server-groups)
        /// * [API documentation](https://help.zscaler.com/zpa/configuring-server-groups-using-api)
        /// 
        /// Use the **zpa_server_group** data source to get information about a server group created in the Zscaler Private Access cloud. This data source can then be referenced in an application segment, application server and Access Policy rule.
        /// 
        /// **NOTE:** To ensure consistent search results across data sources, please avoid using multiple spaces or special characters in your search queries.
        /// 
        /// ## Zenith Community - ZPA Server Groups
        /// 
        /// ![ZPA Terraform provider Video Series Ep4 - Server Groups](https://community.zscaler.com/zenith/s/question/0D54u00009evlEmCAI/video-zpa-terraform-provider-video-series-ep4-server-groups)
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Zpa = zscaler.PulumiPackage.Zpa;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // ZPA Server Group Data Source
        ///     var example = Zpa.GetServerGroup.Invoke(new()
        ///     {
        ///         Name = "server_group_name",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetServerGroupResult> InvokeAsync(GetServerGroupArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetServerGroupResult>("zpa:index/getServerGroup:getServerGroup", args ?? new GetServerGroupArgs(), options.WithDefaults());

        /// <summary>
        /// * [Official documentation](https://help.zscaler.com/zpa/about-server-groups)
        /// * [API documentation](https://help.zscaler.com/zpa/configuring-server-groups-using-api)
        /// 
        /// Use the **zpa_server_group** data source to get information about a server group created in the Zscaler Private Access cloud. This data source can then be referenced in an application segment, application server and Access Policy rule.
        /// 
        /// **NOTE:** To ensure consistent search results across data sources, please avoid using multiple spaces or special characters in your search queries.
        /// 
        /// ## Zenith Community - ZPA Server Groups
        /// 
        /// ![ZPA Terraform provider Video Series Ep4 - Server Groups](https://community.zscaler.com/zenith/s/question/0D54u00009evlEmCAI/video-zpa-terraform-provider-video-series-ep4-server-groups)
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Zpa = zscaler.PulumiPackage.Zpa;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // ZPA Server Group Data Source
        ///     var example = Zpa.GetServerGroup.Invoke(new()
        ///     {
        ///         Name = "server_group_name",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetServerGroupResult> Invoke(GetServerGroupInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetServerGroupResult>("zpa:index/getServerGroup:getServerGroup", args ?? new GetServerGroupInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// * [Official documentation](https://help.zscaler.com/zpa/about-server-groups)
        /// * [API documentation](https://help.zscaler.com/zpa/configuring-server-groups-using-api)
        /// 
        /// Use the **zpa_server_group** data source to get information about a server group created in the Zscaler Private Access cloud. This data source can then be referenced in an application segment, application server and Access Policy rule.
        /// 
        /// **NOTE:** To ensure consistent search results across data sources, please avoid using multiple spaces or special characters in your search queries.
        /// 
        /// ## Zenith Community - ZPA Server Groups
        /// 
        /// ![ZPA Terraform provider Video Series Ep4 - Server Groups](https://community.zscaler.com/zenith/s/question/0D54u00009evlEmCAI/video-zpa-terraform-provider-video-series-ep4-server-groups)
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Zpa = zscaler.PulumiPackage.Zpa;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // ZPA Server Group Data Source
        ///     var example = Zpa.GetServerGroup.Invoke(new()
        ///     {
        ///         Name = "server_group_name",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetServerGroupResult> Invoke(GetServerGroupInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetServerGroupResult>("zpa:index/getServerGroup:getServerGroup", args ?? new GetServerGroupInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetServerGroupArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public string? Id { get; set; }

        [Input("microtenantId")]
        public string? MicrotenantId { get; set; }

        [Input("microtenantName")]
        public string? MicrotenantName { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        public GetServerGroupArgs()
        {
        }
        public static new GetServerGroupArgs Empty => new GetServerGroupArgs();
    }

    public sealed class GetServerGroupInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("microtenantId")]
        public Input<string>? MicrotenantId { get; set; }

        [Input("microtenantName")]
        public Input<string>? MicrotenantName { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetServerGroupInvokeArgs()
        {
        }
        public static new GetServerGroupInvokeArgs Empty => new GetServerGroupInvokeArgs();
    }


    [OutputType]
    public sealed class GetServerGroupResult
    {
        public readonly ImmutableArray<Outputs.GetServerGroupAppConnectorGroupResult> AppConnectorGroups;
        public readonly ImmutableArray<Outputs.GetServerGroupApplicationResult> Applications;
        public readonly string ConfigSpace;
        public readonly string CreationTime;
        public readonly string Description;
        public readonly bool DynamicDiscovery;
        public readonly bool Enabled;
        public readonly string? Id;
        public readonly bool IpAnchored;
        public readonly string? MicrotenantId;
        public readonly string? MicrotenantName;
        public readonly string ModifiedTime;
        public readonly string Modifiedby;
        public readonly string? Name;
        public readonly ImmutableArray<Outputs.GetServerGroupServerResult> Servers;

        [OutputConstructor]
        private GetServerGroupResult(
            ImmutableArray<Outputs.GetServerGroupAppConnectorGroupResult> appConnectorGroups,

            ImmutableArray<Outputs.GetServerGroupApplicationResult> applications,

            string configSpace,

            string creationTime,

            string description,

            bool dynamicDiscovery,

            bool enabled,

            string? id,

            bool ipAnchored,

            string? microtenantId,

            string? microtenantName,

            string modifiedTime,

            string modifiedby,

            string? name,

            ImmutableArray<Outputs.GetServerGroupServerResult> servers)
        {
            AppConnectorGroups = appConnectorGroups;
            Applications = applications;
            ConfigSpace = configSpace;
            CreationTime = creationTime;
            Description = description;
            DynamicDiscovery = dynamicDiscovery;
            Enabled = enabled;
            Id = id;
            IpAnchored = ipAnchored;
            MicrotenantId = microtenantId;
            MicrotenantName = microtenantName;
            ModifiedTime = modifiedTime;
            Modifiedby = modifiedby;
            Name = name;
            Servers = servers;
        }
    }
}
