// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace zscaler.PulumiPackage.Zpa
{
    /// <summary>
    /// * [Official documentation](https://help.zscaler.com/zpa/about-user-portals)
    /// * [API documentation](https://help.zscaler.com/zpa/about-user-portals)
    /// 
    /// The **zpa_user_portal_aup** resource creates a user portal link in the Zscaler Private Access cloud.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Zpa = zscaler.PulumiPackage.Zpa;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var @this = new Zpa.UserPortalAUP("this", new()
    ///     {
    ///         Name = "Org_AUP01",
    ///         Description = "Org_AUP01",
    ///         Enabled = true,
    ///         Aup = "Org_AUP01",
    ///         Email = "company@acme.com",
    ///         PhoneNum = "+1 123-1458",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Zscaler offers a dedicated tool called Zscaler-Terraformer to allow the automated import of ZPA configurations into Terraform-compliant HashiCorp Configuration Language.
    /// 
    /// Visit
    /// 
    /// **zpa_user_portal_aup** can be imported by using `&lt;USER PORTAL ID&gt;` or `&lt;USER PORTAL NAME&gt;` as the import ID.
    /// 
    /// For example:
    /// 
    /// ```sh
    /// $ pulumi import zpa:index/userPortalAUP:UserPortalAUP example &lt;portal_id&gt;
    /// ```
    /// 
    /// or
    /// 
    /// ```sh
    /// $ pulumi import zpa:index/userPortalAUP:UserPortalAUP example &lt;portal_name&gt;
    /// ```
    /// </summary>
    [ZpaResourceType("zpa:index/userPortalAUP:UserPortalAUP")]
    public partial class UserPortalAUP : global::Pulumi.CustomResource
    {
        /// <summary>
        /// - (String)
        /// </summary>
        [Output("aup")]
        public Output<string?> Aup { get; private set; } = null!;

        /// <summary>
        /// - (String) Description of the User Portal AUP
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// - (String)
        /// </summary>
        [Output("email")]
        public Output<string?> Email { get; private set; } = null!;

        /// <summary>
        /// - (Boolean) Whether this User Portal AUP is enabled or not
        /// </summary>
        [Output("enabled")]
        public Output<bool?> Enabled { get; private set; } = null!;

        [Output("microtenantId")]
        public Output<string?> MicrotenantId { get; private set; } = null!;

        /// <summary>
        /// - Name of the User Portal AUP
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// - (String)
        /// </summary>
        [Output("phoneNum")]
        public Output<string?> PhoneNum { get; private set; } = null!;


        /// <summary>
        /// Create a UserPortalAUP resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public UserPortalAUP(string name, UserPortalAUPArgs? args = null, CustomResourceOptions? options = null)
            : base("zpa:index/userPortalAUP:UserPortalAUP", name, args ?? new UserPortalAUPArgs(), MakeResourceOptions(options, ""))
        {
        }

        private UserPortalAUP(string name, Input<string> id, UserPortalAUPState? state = null, CustomResourceOptions? options = null)
            : base("zpa:index/userPortalAUP:UserPortalAUP", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/zscaler",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing UserPortalAUP resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static UserPortalAUP Get(string name, Input<string> id, UserPortalAUPState? state = null, CustomResourceOptions? options = null)
        {
            return new UserPortalAUP(name, id, state, options);
        }
    }

    public sealed class UserPortalAUPArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// - (String)
        /// </summary>
        [Input("aup")]
        public Input<string>? Aup { get; set; }

        /// <summary>
        /// - (String) Description of the User Portal AUP
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// - (String)
        /// </summary>
        [Input("email")]
        public Input<string>? Email { get; set; }

        /// <summary>
        /// - (Boolean) Whether this User Portal AUP is enabled or not
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("microtenantId")]
        public Input<string>? MicrotenantId { get; set; }

        /// <summary>
        /// - Name of the User Portal AUP
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// - (String)
        /// </summary>
        [Input("phoneNum")]
        public Input<string>? PhoneNum { get; set; }

        public UserPortalAUPArgs()
        {
        }
        public static new UserPortalAUPArgs Empty => new UserPortalAUPArgs();
    }

    public sealed class UserPortalAUPState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// - (String)
        /// </summary>
        [Input("aup")]
        public Input<string>? Aup { get; set; }

        /// <summary>
        /// - (String) Description of the User Portal AUP
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// - (String)
        /// </summary>
        [Input("email")]
        public Input<string>? Email { get; set; }

        /// <summary>
        /// - (Boolean) Whether this User Portal AUP is enabled or not
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("microtenantId")]
        public Input<string>? MicrotenantId { get; set; }

        /// <summary>
        /// - Name of the User Portal AUP
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// - (String)
        /// </summary>
        [Input("phoneNum")]
        public Input<string>? PhoneNum { get; set; }

        public UserPortalAUPState()
        {
        }
        public static new UserPortalAUPState Empty => new UserPortalAUPState();
    }
}
