// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace zscaler.PulumiPackage.Zpa.Outputs
{

    [OutputType]
    public sealed class GetCloudConnectorGroupCloudConnectorResult
    {
        public readonly string CreationTime;
        public readonly string Description;
        public readonly bool Enabled;
        public readonly string Fingerprint;
        public readonly string Id;
        public readonly ImmutableArray<object> Ipacls;
        public readonly string IssuedCertId;
        public readonly string ModifiedTime;
        public readonly string Modifiedby;
        public readonly string Name;
        public readonly ImmutableDictionary<string, string> SigningCert;

        [OutputConstructor]
        private GetCloudConnectorGroupCloudConnectorResult(
            string creationTime,

            string description,

            bool enabled,

            string fingerprint,

            string id,

            ImmutableArray<object> ipacls,

            string issuedCertId,

            string modifiedTime,

            string modifiedby,

            string name,

            ImmutableDictionary<string, string> signingCert)
        {
            CreationTime = creationTime;
            Description = description;
            Enabled = enabled;
            Fingerprint = fingerprint;
            Id = id;
            Ipacls = ipacls;
            IssuedCertId = issuedCertId;
            ModifiedTime = modifiedTime;
            Modifiedby = modifiedby;
            Name = name;
            SigningCert = signingCert;
        }
    }
}
