// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Zscaler.Zpa.Inputs
{

    public sealed class CloudBrowserIsolationExternalProfileSecurityControlArgs : global::Pulumi.ResourceArgs
    {
        [Input("allowPrinting")]
        public Input<bool>? AllowPrinting { get; set; }

        [Input("copyPaste")]
        public Input<string>? CopyPaste { get; set; }

        [Input("documentViewer")]
        public Input<bool>? DocumentViewer { get; set; }

        [Input("localRender")]
        public Input<bool>? LocalRender { get; set; }

        [Input("restrictKeystrokes")]
        public Input<bool>? RestrictKeystrokes { get; set; }

        [Input("uploadDownload")]
        public Input<string>? UploadDownload { get; set; }

        public CloudBrowserIsolationExternalProfileSecurityControlArgs()
        {
        }
        public static new CloudBrowserIsolationExternalProfileSecurityControlArgs Empty => new CloudBrowserIsolationExternalProfileSecurityControlArgs();
    }
}
