name: ci

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'dependabot/**'
    tags-ignore:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Unshallow clone for tags
      #   run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'provider/go.mod'
          cache-dependency-path: 'provider/go.sum'
          cache: true
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: pulumi/pulumictl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: dirty-check
      #   run: |
      #     make check-dirty