// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * * [Official documentation](https://help.zscaler.com/zpa/about-connector-groups)
 * * [API documentation](https://help.zscaler.com/zpa/configuring-app-connector-groups-using-api)
 *
 * Use the **zpa_app_connector_group** data source to get information about a app connector group in the Zscaler Private Access cloud. This data source can then be referenced in an App Connector Group. This data source can then be referenced in the following resources:
 *
 * **NOTE:** To ensure consistent search results across data sources, please avoid using multiple spaces or special characters in your search queries.
 *
 * * Create a server group
 * * Provisioning Key
 * * Access policy rule
 *
 * ## Zenith Community - ZPA App Connector Group
 *
 * ![ZPA Terraform provider Video Series Ep2 - Connector Groups](https://community.zscaler.com/zenith/s/question/0D54u00009evlEoCAI/video-zpa-terraform-provider-video-series-ep2-connector-groups)
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@bdzscaler/pulumi-zpa";
 *
 * // ZPA App Connector Group Data Source
 * const foo = zpa.getAppConnectorGroup({
 *     name: "DataCenter",
 * });
 * ```
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@bdzscaler/pulumi-zpa";
 *
 * // ZPA App Connector Group Data Source
 * const foo = zpa.getAppConnectorGroup({
 *     id: "123456789",
 * });
 * ```
 */
export function getAppConnectorGroup(args?: GetAppConnectorGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetAppConnectorGroupResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("zpa:index/getAppConnectorGroup:getAppConnectorGroup", {
        "id": args.id,
        "microtenantId": args.microtenantId,
        "microtenantName": args.microtenantName,
        "name": args.name,
        "overrideVersionProfile": args.overrideVersionProfile,
    }, opts);
}

/**
 * A collection of arguments for invoking getAppConnectorGroup.
 */
export interface GetAppConnectorGroupArgs {
    id?: string;
    microtenantId?: string;
    microtenantName?: string;
    name?: string;
    overrideVersionProfile?: boolean;
}

/**
 * A collection of values returned by getAppConnectorGroup.
 */
export interface GetAppConnectorGroupResult {
    readonly cityCountry: string;
    readonly connectors: outputs.GetAppConnectorGroupConnector[];
    readonly countryCode: string;
    readonly creationTime: string;
    readonly description: string;
    readonly dnsQueryType: string;
    readonly enabled: boolean;
    readonly geoLocationId: string;
    readonly id?: string;
    readonly latitude: string;
    readonly location: string;
    readonly longitude: string;
    readonly lssAppConnectorGroup: boolean;
    readonly microtenantId?: string;
    readonly microtenantName?: string;
    readonly modifiedTime: string;
    readonly modifiedby: string;
    readonly name?: string;
    readonly overrideVersionProfile?: boolean;
    readonly serverGroups: outputs.GetAppConnectorGroupServerGroup[];
    readonly tcpQuickAckApp: boolean;
    readonly tcpQuickAckAssistant: boolean;
    readonly tcpQuickAckReadAssistant: boolean;
    readonly upgradeDay: string;
    readonly upgradeTimeInSecs: string;
    readonly useInDrMode: boolean;
    readonly versionProfileId: string;
    readonly versionProfileName: string;
    readonly versionProfileVisibilityScope: string;
}
/**
 * * [Official documentation](https://help.zscaler.com/zpa/about-connector-groups)
 * * [API documentation](https://help.zscaler.com/zpa/configuring-app-connector-groups-using-api)
 *
 * Use the **zpa_app_connector_group** data source to get information about a app connector group in the Zscaler Private Access cloud. This data source can then be referenced in an App Connector Group. This data source can then be referenced in the following resources:
 *
 * **NOTE:** To ensure consistent search results across data sources, please avoid using multiple spaces or special characters in your search queries.
 *
 * * Create a server group
 * * Provisioning Key
 * * Access policy rule
 *
 * ## Zenith Community - ZPA App Connector Group
 *
 * ![ZPA Terraform provider Video Series Ep2 - Connector Groups](https://community.zscaler.com/zenith/s/question/0D54u00009evlEoCAI/video-zpa-terraform-provider-video-series-ep2-connector-groups)
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@bdzscaler/pulumi-zpa";
 *
 * // ZPA App Connector Group Data Source
 * const foo = zpa.getAppConnectorGroup({
 *     name: "DataCenter",
 * });
 * ```
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@bdzscaler/pulumi-zpa";
 *
 * // ZPA App Connector Group Data Source
 * const foo = zpa.getAppConnectorGroup({
 *     id: "123456789",
 * });
 * ```
 */
export function getAppConnectorGroupOutput(args?: GetAppConnectorGroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAppConnectorGroupResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("zpa:index/getAppConnectorGroup:getAppConnectorGroup", {
        "id": args.id,
        "microtenantId": args.microtenantId,
        "microtenantName": args.microtenantName,
        "name": args.name,
        "overrideVersionProfile": args.overrideVersionProfile,
    }, opts);
}

/**
 * A collection of arguments for invoking getAppConnectorGroup.
 */
export interface GetAppConnectorGroupOutputArgs {
    id?: pulumi.Input<string>;
    microtenantId?: pulumi.Input<string>;
    microtenantName?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    overrideVersionProfile?: pulumi.Input<boolean>;
}
