// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Use the **zpa_customer_version_profile** data source to get information about all customer version profiles from the Zscaler Private Access cloud. This data source can be associated with an App Connector Group within the parameter `versionProfileId` or `versionProfileName`
 *
 * The customer version profile IDs are:
 *
 * * `Default` = `0`
 * * `Previous Default` = `1`
 * * `New Release` = `2`
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@pulumi/zpa";
 *
 * const default = zpa.getCustomerVersionProfile({
 *     name: "Default",
 * });
 * const previousDefault = zpa.getCustomerVersionProfile({
 *     name: "Previous Default",
 * });
 * const newRelease = zpa.getCustomerVersionProfile({
 *     name: "New Release",
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getCustomerVersionProfile(args: GetCustomerVersionProfileArgs, opts?: pulumi.InvokeOptions): Promise<GetCustomerVersionProfileResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("zpa:index/getCustomerVersionProfile:getCustomerVersionProfile", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getCustomerVersionProfile.
 */
export interface GetCustomerVersionProfileArgs {
    /**
     * The name of the enrollment certificate to be exported.
     */
    name: string;
}

/**
 * A collection of values returned by getCustomerVersionProfile.
 */
export interface GetCustomerVersionProfileResult {
    /**
     * (string)
     */
    readonly creationTime: string;
    readonly customScopeCustomerIds: outputs.GetCustomerVersionProfileCustomScopeCustomerId[];
    readonly customerId: string;
    /**
     * (string)
     */
    readonly description: string;
    readonly id: string;
    /**
     * (string)
     */
    readonly modifiedBy: string;
    /**
     * (string)
     */
    readonly modifiedTime: string;
    readonly name: string;
    readonly upgradePriority: string;
    readonly versions: outputs.GetCustomerVersionProfileVersion[];
    readonly visibilityScope: string;
}
/**
 * Use the **zpa_customer_version_profile** data source to get information about all customer version profiles from the Zscaler Private Access cloud. This data source can be associated with an App Connector Group within the parameter `versionProfileId` or `versionProfileName`
 *
 * The customer version profile IDs are:
 *
 * * `Default` = `0`
 * * `Previous Default` = `1`
 * * `New Release` = `2`
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@pulumi/zpa";
 *
 * const default = zpa.getCustomerVersionProfile({
 *     name: "Default",
 * });
 * const previousDefault = zpa.getCustomerVersionProfile({
 *     name: "Previous Default",
 * });
 * const newRelease = zpa.getCustomerVersionProfile({
 *     name: "New Release",
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getCustomerVersionProfileOutput(args: GetCustomerVersionProfileOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetCustomerVersionProfileResult> {
    return pulumi.output(args).apply((a: any) => getCustomerVersionProfile(a, opts))
}

/**
 * A collection of arguments for invoking getCustomerVersionProfile.
 */
export interface GetCustomerVersionProfileOutputArgs {
    /**
     * The name of the enrollment certificate to be exported.
     */
    name: pulumi.Input<string>;
}
