// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * * [Official documentation](https://help.zscaler.com/zpa/about-privileged-capabilities-policy)
 * * [API documentation](https://help.zscaler.com/zpa/configuring-privileged-policies-using-api)
 *
 * The **zpa_policy_portal_access_rule** resource creates a Privileged Portal Policy Capabilities Rule in the Zscaler Private Access cloud.
 *
 *   ⚠️ **WARNING:**: The attribute ``ruleOrder`` is now deprecated in favor of the new resource  ``policyAccessRuleReorder``
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@bdzscaler/pulumi-zpa";
 *
 * const emailUserSso = zpa.getSAMLAttribute({
 *     name: "Email_BD_Okta_Users",
 *     idpName: "BD_Okta_Users",
 * });
 * const _this = zpa.getIdPController({
 *     name: "BD_Okta_Users",
 * });
 * const a000 = zpa.getSCIMGroups({
 *     idpName: "BD_Okta_Users",
 *     name: "A000",
 * });
 * const b000 = zpa.getSCIMGroups({
 *     idpName: "BD_Okta_Users",
 *     name: "B000",
 * });
 * const example = new zpa.PolicyPortalAccessRule("example", {
 *     name: "Portal Access Rule",
 *     description: "Allow portal access with specific capabilities",
 *     action: "CHECK_PRIVILEGED_PORTAL_CAPABILITIES",
 *     privilegedPortalCapabilities: {
 *         deleteFile: true,
 *         accessUninspectedFile: true,
 *         requestApprovals: true,
 *         reviewApprovals: true,
 *     },
 *     conditions: [
 *         {
 *             operator: "OR",
 *             operands: [{
 *                 objectType: "PRIVILEGE_PORTAL",
 *                 values: ["216196257331387235"],
 *             }],
 *         },
 *         {
 *             operator: "OR",
 *             operands: [{
 *                 objectType: "COUNTRY_CODE",
 *                 entryValues: [
 *                     {
 *                         lhs: "BR",
 *                         rhs: "true",
 *                     },
 *                     {
 *                         lhs: "CA",
 *                         rhs: "true",
 *                     },
 *                 ],
 *             }],
 *         },
 *         {
 *             operator: "OR",
 *             operands: [
 *                 {
 *                     objectType: "SAML",
 *                     entryValues: [{
 *                         rhs: "user1@acme.com",
 *                         lhs: emailUserSso.then(emailUserSso => emailUserSso.id),
 *                     }],
 *                 },
 *                 {
 *                     objectType: "SCIM_GROUP",
 *                     entryValues: [
 *                         {
 *                             rhs: a000.then(a000 => a000.id),
 *                             lhs: _this.then(_this => _this.id),
 *                         },
 *                         {
 *                             rhs: b000.then(b000 => b000.id),
 *                             lhs: _this.then(_this => _this.id),
 *                         },
 *                     ],
 *                 },
 *             ],
 *         },
 *     ],
 * });
 * ```
 *
 * ## LHS and RHS Values
 *
 * | Object Type | LHS| RHS| VALUES
 * |----------|-----------|----------|----------
 * | PRIVILEGE_PORTAL  | `NA` | `NA` | ``userPortalId`` |
 * | SAML | ``samlAttributeId``  | ``attributeValueToMatch`` |
 * | SCIM | ``scimAttributeId``  | ``attributeValueToMatch``  |
 * | SCIM_GROUP | ``scimGroupAttributeId``  | ``attributeValueToMatch``  |
 * | COUNTRY_CODE | [2 Letter ISO3166 Alpha2](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes)  | ``"true"`` |
 *
 * ## Import
 *
 * Zscaler offers a dedicated tool called Zscaler-Terraformer to allow the automated import of ZPA configurations into Terraform-compliant HashiCorp Configuration Language.
 *
 * Visit
 *
 * Policy access capability can be imported by using `<RULE ID>` as the import ID.
 *
 * For example:
 *
 * ```sh
 * $ pulumi import zpa:index/policyPortalAccessRule:PolicyPortalAccessRule example <rule_id>
 * ```
 */
export class PolicyPortalAccessRule extends pulumi.CustomResource {
    /**
     * Get an existing PolicyPortalAccessRule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PolicyPortalAccessRuleState, opts?: pulumi.CustomResourceOptions): PolicyPortalAccessRule {
        return new PolicyPortalAccessRule(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'zpa:index/policyPortalAccessRule:PolicyPortalAccessRule';

    /**
     * Returns true if the given object is an instance of PolicyPortalAccessRule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PolicyPortalAccessRule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PolicyPortalAccessRule.__pulumiType;
    }

    /**
     * This is for providing the rule action. Supported value: `CHECK_CAPABILITIES`
     */
    declare public readonly action: pulumi.Output<string | undefined>;
    /**
     * This is for proviidng the set of conditions for the policy.
     */
    declare public readonly conditions: pulumi.Output<outputs.PolicyPortalAccessRuleCondition[] | undefined>;
    /**
     * This is the description of the access policy.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    declare public readonly microtenantId: pulumi.Output<string | undefined>;
    /**
     * This is the name of the policy rule.
     */
    declare public readonly name: pulumi.Output<string>;
    declare public /*out*/ readonly policySetId: pulumi.Output<string>;
    declare public readonly privilegedPortalCapabilities: pulumi.Output<outputs.PolicyPortalAccessRulePrivilegedPortalCapabilities>;

    /**
     * Create a PolicyPortalAccessRule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PolicyPortalAccessRuleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PolicyPortalAccessRuleArgs | PolicyPortalAccessRuleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PolicyPortalAccessRuleState | undefined;
            resourceInputs["action"] = state?.action;
            resourceInputs["conditions"] = state?.conditions;
            resourceInputs["description"] = state?.description;
            resourceInputs["microtenantId"] = state?.microtenantId;
            resourceInputs["name"] = state?.name;
            resourceInputs["policySetId"] = state?.policySetId;
            resourceInputs["privilegedPortalCapabilities"] = state?.privilegedPortalCapabilities;
        } else {
            const args = argsOrState as PolicyPortalAccessRuleArgs | undefined;
            resourceInputs["action"] = args?.action;
            resourceInputs["conditions"] = args?.conditions;
            resourceInputs["description"] = args?.description;
            resourceInputs["microtenantId"] = args?.microtenantId;
            resourceInputs["name"] = args?.name;
            resourceInputs["privilegedPortalCapabilities"] = args?.privilegedPortalCapabilities;
            resourceInputs["policySetId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PolicyPortalAccessRule.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering PolicyPortalAccessRule resources.
 */
export interface PolicyPortalAccessRuleState {
    /**
     * This is for providing the rule action. Supported value: `CHECK_CAPABILITIES`
     */
    action?: pulumi.Input<string>;
    /**
     * This is for proviidng the set of conditions for the policy.
     */
    conditions?: pulumi.Input<pulumi.Input<inputs.PolicyPortalAccessRuleCondition>[]>;
    /**
     * This is the description of the access policy.
     */
    description?: pulumi.Input<string>;
    microtenantId?: pulumi.Input<string>;
    /**
     * This is the name of the policy rule.
     */
    name?: pulumi.Input<string>;
    policySetId?: pulumi.Input<string>;
    privilegedPortalCapabilities?: pulumi.Input<inputs.PolicyPortalAccessRulePrivilegedPortalCapabilities>;
}

/**
 * The set of arguments for constructing a PolicyPortalAccessRule resource.
 */
export interface PolicyPortalAccessRuleArgs {
    /**
     * This is for providing the rule action. Supported value: `CHECK_CAPABILITIES`
     */
    action?: pulumi.Input<string>;
    /**
     * This is for proviidng the set of conditions for the policy.
     */
    conditions?: pulumi.Input<pulumi.Input<inputs.PolicyPortalAccessRuleCondition>[]>;
    /**
     * This is the description of the access policy.
     */
    description?: pulumi.Input<string>;
    microtenantId?: pulumi.Input<string>;
    /**
     * This is the name of the policy rule.
     */
    name?: pulumi.Input<string>;
    privilegedPortalCapabilities?: pulumi.Input<inputs.PolicyPortalAccessRulePrivilegedPortalCapabilities>;
}
