// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * * [Official documentation](https://help.zscaler.com/zpa/about-timeout-policy)
 * * [API documentation](https://help.zscaler.com/zpa/configuring-timeout-policies-using-api)
 *
 * The **zpa_policy_timeout_rule** resource creates a policy timeout rule in the Zscaler Private Access cloud.
 *
 *   ⚠️ **WARNING:**: The attribute ``ruleOrder`` is now deprecated in favor of the new resource  ``policyAccessRuleReorder``
 *
 * ## Example Usage
 *
 * ## LHS and RHS Values
 *
 * | Object Type | LHS| RHS
 * |----------|-----------|----------
 * | APP | ``"id"`` | ``applicationSegmentId`` |
 * | APP_GROUP | ``"id"`` | ``segmentGroupId``|
 * | CLIENT_TYPE | ``"id"`` | ``zpnClientTypeExporter``, ``zpnClientTypeBrowserIsolation``, ``zpnClientTypeZapp``, ``zpnClientTypeZappPartner``  |
 * | IDP | ``"id"`` | ``identityProviderId`` |
 * | SAML | ``samlAttributeId``  | ``attributeValueToMatch`` |
 * | SCIM | ``scimAttributeId``  | ``attributeValueToMatch``  |
 * | SCIM_GROUP | ``scimGroupAttributeId``  | ``attributeValueToMatch``  |
 * | PLATFORM | ``mac``, ``ios``, ``windows``, ``android``, ``linux`` | ``"true"`` / ``"false"`` |
 * | POSTURE | ``postureUdid``  | ``"true"`` / ``"false"`` |
 *
 * ## Import
 *
 * Zscaler offers a dedicated tool called Zscaler-Terraformer to allow the automated import of ZPA configurations into Terraform-compliant HashiCorp Configuration Language.
 *
 * Visit
 *
 * Policy access timeout can be imported by using `<POLICY TIMEOUT RULE ID>` as the import ID.
 *
 * For example:
 *
 * ```sh
 * $ pulumi import zpa:index/policyAccessTimeOutRule:PolicyAccessTimeOutRule example <policy_timeout_rule_id>
 * ```
 */
export class PolicyAccessTimeOutRule extends pulumi.CustomResource {
    /**
     * Get an existing PolicyAccessTimeOutRule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PolicyAccessTimeOutRuleState, opts?: pulumi.CustomResourceOptions): PolicyAccessTimeOutRule {
        return new PolicyAccessTimeOutRule(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'zpa:index/policyAccessTimeOutRule:PolicyAccessTimeOutRule';

    /**
     * Returns true if the given object is an instance of PolicyAccessTimeOutRule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PolicyAccessTimeOutRule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PolicyAccessTimeOutRule.__pulumiType;
    }

    /**
     * This is for providing the rule action.
     */
    declare public readonly action: pulumi.Output<string | undefined>;
    /**
     * This field defines the description of the server.
     */
    declare public readonly actionId: pulumi.Output<string | undefined>;
    declare public readonly bypassDefaultRule: pulumi.Output<boolean>;
    /**
     * This is for proviidng the set of conditions for the policy.
     */
    declare public readonly conditions: pulumi.Output<outputs.PolicyAccessTimeOutRuleCondition[] | undefined>;
    /**
     * This is for providing a customer message for the user.
     */
    declare public readonly customMsg: pulumi.Output<string>;
    /**
     * This is for providing a customer message for the user.
     */
    declare public readonly defaultRule: pulumi.Output<boolean>;
    /**
     * This is the description of the access policy.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    declare public readonly lssDefaultRule: pulumi.Output<boolean | undefined>;
    declare public readonly microtenantId: pulumi.Output<string>;
    /**
     * This is the name of the policy.
     */
    declare public readonly name: pulumi.Output<string>;
    declare public readonly operator: pulumi.Output<string>;
    declare public readonly policySetId: pulumi.Output<string>;
    declare public readonly policyType: pulumi.Output<string>;
    declare public readonly priority: pulumi.Output<string>;
    declare public readonly reauthDefaultRule: pulumi.Output<boolean>;
    declare public readonly reauthIdleTimeout: pulumi.Output<string | undefined>;
    declare public readonly reauthTimeout: pulumi.Output<string | undefined>;
    /**
     * @deprecated The `ruleOrder` field is now deprecated for all zpa access policy resources in favor of the resource `zpa.PolicyAccessReorderRule`
     */
    declare public readonly ruleOrder: pulumi.Output<string>;
    declare public readonly zpnCbiProfileId: pulumi.Output<string>;
    declare public readonly zpnInspectionProfileId: pulumi.Output<string>;
    declare public readonly zpnIsolationProfileId: pulumi.Output<string>;

    /**
     * Create a PolicyAccessTimeOutRule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PolicyAccessTimeOutRuleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PolicyAccessTimeOutRuleArgs | PolicyAccessTimeOutRuleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PolicyAccessTimeOutRuleState | undefined;
            resourceInputs["action"] = state?.action;
            resourceInputs["actionId"] = state?.actionId;
            resourceInputs["bypassDefaultRule"] = state?.bypassDefaultRule;
            resourceInputs["conditions"] = state?.conditions;
            resourceInputs["customMsg"] = state?.customMsg;
            resourceInputs["defaultRule"] = state?.defaultRule;
            resourceInputs["description"] = state?.description;
            resourceInputs["lssDefaultRule"] = state?.lssDefaultRule;
            resourceInputs["microtenantId"] = state?.microtenantId;
            resourceInputs["name"] = state?.name;
            resourceInputs["operator"] = state?.operator;
            resourceInputs["policySetId"] = state?.policySetId;
            resourceInputs["policyType"] = state?.policyType;
            resourceInputs["priority"] = state?.priority;
            resourceInputs["reauthDefaultRule"] = state?.reauthDefaultRule;
            resourceInputs["reauthIdleTimeout"] = state?.reauthIdleTimeout;
            resourceInputs["reauthTimeout"] = state?.reauthTimeout;
            resourceInputs["ruleOrder"] = state?.ruleOrder;
            resourceInputs["zpnCbiProfileId"] = state?.zpnCbiProfileId;
            resourceInputs["zpnInspectionProfileId"] = state?.zpnInspectionProfileId;
            resourceInputs["zpnIsolationProfileId"] = state?.zpnIsolationProfileId;
        } else {
            const args = argsOrState as PolicyAccessTimeOutRuleArgs | undefined;
            resourceInputs["action"] = args?.action;
            resourceInputs["actionId"] = args?.actionId;
            resourceInputs["bypassDefaultRule"] = args?.bypassDefaultRule;
            resourceInputs["conditions"] = args?.conditions;
            resourceInputs["customMsg"] = args?.customMsg;
            resourceInputs["defaultRule"] = args?.defaultRule;
            resourceInputs["description"] = args?.description;
            resourceInputs["lssDefaultRule"] = args?.lssDefaultRule;
            resourceInputs["microtenantId"] = args?.microtenantId;
            resourceInputs["name"] = args?.name;
            resourceInputs["operator"] = args?.operator;
            resourceInputs["policySetId"] = args?.policySetId;
            resourceInputs["policyType"] = args?.policyType;
            resourceInputs["priority"] = args?.priority;
            resourceInputs["reauthDefaultRule"] = args?.reauthDefaultRule;
            resourceInputs["reauthIdleTimeout"] = args?.reauthIdleTimeout;
            resourceInputs["reauthTimeout"] = args?.reauthTimeout;
            resourceInputs["ruleOrder"] = args?.ruleOrder;
            resourceInputs["zpnCbiProfileId"] = args?.zpnCbiProfileId;
            resourceInputs["zpnInspectionProfileId"] = args?.zpnInspectionProfileId;
            resourceInputs["zpnIsolationProfileId"] = args?.zpnIsolationProfileId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PolicyAccessTimeOutRule.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering PolicyAccessTimeOutRule resources.
 */
export interface PolicyAccessTimeOutRuleState {
    /**
     * This is for providing the rule action.
     */
    action?: pulumi.Input<string>;
    /**
     * This field defines the description of the server.
     */
    actionId?: pulumi.Input<string>;
    bypassDefaultRule?: pulumi.Input<boolean>;
    /**
     * This is for proviidng the set of conditions for the policy.
     */
    conditions?: pulumi.Input<pulumi.Input<inputs.PolicyAccessTimeOutRuleCondition>[]>;
    /**
     * This is for providing a customer message for the user.
     */
    customMsg?: pulumi.Input<string>;
    /**
     * This is for providing a customer message for the user.
     */
    defaultRule?: pulumi.Input<boolean>;
    /**
     * This is the description of the access policy.
     */
    description?: pulumi.Input<string>;
    lssDefaultRule?: pulumi.Input<boolean>;
    microtenantId?: pulumi.Input<string>;
    /**
     * This is the name of the policy.
     */
    name?: pulumi.Input<string>;
    operator?: pulumi.Input<string>;
    policySetId?: pulumi.Input<string>;
    policyType?: pulumi.Input<string>;
    priority?: pulumi.Input<string>;
    reauthDefaultRule?: pulumi.Input<boolean>;
    reauthIdleTimeout?: pulumi.Input<string>;
    reauthTimeout?: pulumi.Input<string>;
    /**
     * @deprecated The `ruleOrder` field is now deprecated for all zpa access policy resources in favor of the resource `zpa.PolicyAccessReorderRule`
     */
    ruleOrder?: pulumi.Input<string>;
    zpnCbiProfileId?: pulumi.Input<string>;
    zpnInspectionProfileId?: pulumi.Input<string>;
    zpnIsolationProfileId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a PolicyAccessTimeOutRule resource.
 */
export interface PolicyAccessTimeOutRuleArgs {
    /**
     * This is for providing the rule action.
     */
    action?: pulumi.Input<string>;
    /**
     * This field defines the description of the server.
     */
    actionId?: pulumi.Input<string>;
    bypassDefaultRule?: pulumi.Input<boolean>;
    /**
     * This is for proviidng the set of conditions for the policy.
     */
    conditions?: pulumi.Input<pulumi.Input<inputs.PolicyAccessTimeOutRuleCondition>[]>;
    /**
     * This is for providing a customer message for the user.
     */
    customMsg?: pulumi.Input<string>;
    /**
     * This is for providing a customer message for the user.
     */
    defaultRule?: pulumi.Input<boolean>;
    /**
     * This is the description of the access policy.
     */
    description?: pulumi.Input<string>;
    lssDefaultRule?: pulumi.Input<boolean>;
    microtenantId?: pulumi.Input<string>;
    /**
     * This is the name of the policy.
     */
    name?: pulumi.Input<string>;
    operator?: pulumi.Input<string>;
    policySetId?: pulumi.Input<string>;
    policyType?: pulumi.Input<string>;
    priority?: pulumi.Input<string>;
    reauthDefaultRule?: pulumi.Input<boolean>;
    reauthIdleTimeout?: pulumi.Input<string>;
    reauthTimeout?: pulumi.Input<string>;
    /**
     * @deprecated The `ruleOrder` field is now deprecated for all zpa access policy resources in favor of the resource `zpa.PolicyAccessReorderRule`
     */
    ruleOrder?: pulumi.Input<string>;
    zpnCbiProfileId?: pulumi.Input<string>;
    zpnInspectionProfileId?: pulumi.Input<string>;
    zpnIsolationProfileId?: pulumi.Input<string>;
}
