// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * * [Official documentation](https://help.zscaler.com/zpa/about-private-cloud-controller-groups)
 * * [API documentation](https://help.zscaler.com/zpa/about-private-cloud-controller-groups)
 *
 * The **zpa_private_cloud_group** resource creates a private cloud group in the Zscaler Private Access cloud.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@bdzscaler/pulumi-zpa";
 *
 * const _this = new zpa.PrivateCloudGroup("this", {
 *     name: "PrivateCloudGroup01",
 *     description: "Example private cloud group",
 *     enabled: true,
 *     cityCountry: "San Jose, US",
 *     latitude: "37.33874",
 *     longitude: "-121.8852525",
 *     location: "San Jose, CA, USA",
 *     upgradeDay: "SUNDAY",
 *     upgradeTimeInSecs: "66600",
 *     siteId: "72058304855088543",
 *     versionProfileId: "0",
 *     overrideVersionProfile: true,
 *     isPublic: "TRUE",
 * });
 * ```
 *
 * ## Import
 *
 * Zscaler offers a dedicated tool called Zscaler-Terraformer to allow the automated import of ZPA configurations into Terraform-compliant HashiCorp Configuration Language.
 *
 * Visit
 *
 * Private Cloud Group can be imported by using `<GROUP ID>` or `<GROUP NAME>` as the import ID.
 *
 * ```sh
 * $ pulumi import zpa:index/privateCloudGroup:PrivateCloudGroup example <group_id>
 * ```
 *
 * or
 *
 * ```sh
 * $ pulumi import zpa:index/privateCloudGroup:PrivateCloudGroup example <group_name>
 * ```
 */
export class PrivateCloudGroup extends pulumi.CustomResource {
    /**
     * Get an existing PrivateCloudGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PrivateCloudGroupState, opts?: pulumi.CustomResourceOptions): PrivateCloudGroup {
        return new PrivateCloudGroup(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'zpa:index/privateCloudGroup:PrivateCloudGroup';

    /**
     * Returns true if the given object is an instance of PrivateCloudGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PrivateCloudGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PrivateCloudGroup.__pulumiType;
    }

    /**
     * - City and country of the Private Cloud Group
     */
    declare public readonly cityCountry: pulumi.Output<string | undefined>;
    /**
     * - Country code of the Private Cloud Group
     */
    declare public readonly countryCode: pulumi.Output<string>;
    /**
     * - Description of the Private Cloud Group
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * - Whether this Private Cloud Group is enabled or not
     */
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    /**
     * - Whether the Private Cloud Group is public
     */
    declare public readonly isPublic: pulumi.Output<string>;
    /**
     * - Latitude of the Private Cloud Group. Integer or decimal. With values in the range of -90 to 90
     */
    declare public readonly latitude: pulumi.Output<string | undefined>;
    /**
     * - Location of the Private Cloud Group
     */
    declare public readonly location: pulumi.Output<string | undefined>;
    /**
     * - Longitude of the Private Cloud Group. Integer or decimal. With values in the range of -180 to 180
     */
    declare public readonly longitude: pulumi.Output<string | undefined>;
    /**
     * - Microtenant ID for the Private Cloud Group
     */
    declare public readonly microtenantId: pulumi.Output<string | undefined>;
    /**
     * - Name of the Private Cloud Group
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * - Whether the default version profile of the Private Cloud Group is applied or overridden
     */
    declare public readonly overrideVersionProfile: pulumi.Output<boolean | undefined>;
    /**
     * - Site ID for the Private Cloud Group
     */
    declare public readonly siteId: pulumi.Output<string | undefined>;
    /**
     * - Private Cloud Controllers in this group will attempt to update to a newer version of the software during this specified day. Supported values: `SUNDAY`, `MONDAY`, `TUESDAY`, `WEDNESDAY`, `THURSDAY`, `FRIDAY`, `SATURDAY`
     */
    declare public readonly upgradeDay: pulumi.Output<string | undefined>;
    /**
     * - Private Cloud Controllers in this group will attempt to update to a newer version of the software during this specified time. Integer in seconds (i.e., -66600). The integer should be greater than or equal to 0 and less than 86400, in 15 minute intervals
     */
    declare public readonly upgradeTimeInSecs: pulumi.Output<string | undefined>;
    /**
     * - ID of the version profile for the Private Cloud Group
     */
    declare public readonly versionProfileId: pulumi.Output<string | undefined>;

    /**
     * Create a PrivateCloudGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PrivateCloudGroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PrivateCloudGroupArgs | PrivateCloudGroupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PrivateCloudGroupState | undefined;
            resourceInputs["cityCountry"] = state?.cityCountry;
            resourceInputs["countryCode"] = state?.countryCode;
            resourceInputs["description"] = state?.description;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["isPublic"] = state?.isPublic;
            resourceInputs["latitude"] = state?.latitude;
            resourceInputs["location"] = state?.location;
            resourceInputs["longitude"] = state?.longitude;
            resourceInputs["microtenantId"] = state?.microtenantId;
            resourceInputs["name"] = state?.name;
            resourceInputs["overrideVersionProfile"] = state?.overrideVersionProfile;
            resourceInputs["siteId"] = state?.siteId;
            resourceInputs["upgradeDay"] = state?.upgradeDay;
            resourceInputs["upgradeTimeInSecs"] = state?.upgradeTimeInSecs;
            resourceInputs["versionProfileId"] = state?.versionProfileId;
        } else {
            const args = argsOrState as PrivateCloudGroupArgs | undefined;
            resourceInputs["cityCountry"] = args?.cityCountry;
            resourceInputs["countryCode"] = args?.countryCode;
            resourceInputs["description"] = args?.description;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["isPublic"] = args?.isPublic;
            resourceInputs["latitude"] = args?.latitude;
            resourceInputs["location"] = args?.location;
            resourceInputs["longitude"] = args?.longitude;
            resourceInputs["microtenantId"] = args?.microtenantId;
            resourceInputs["name"] = args?.name;
            resourceInputs["overrideVersionProfile"] = args?.overrideVersionProfile;
            resourceInputs["siteId"] = args?.siteId;
            resourceInputs["upgradeDay"] = args?.upgradeDay;
            resourceInputs["upgradeTimeInSecs"] = args?.upgradeTimeInSecs;
            resourceInputs["versionProfileId"] = args?.versionProfileId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PrivateCloudGroup.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering PrivateCloudGroup resources.
 */
export interface PrivateCloudGroupState {
    /**
     * - City and country of the Private Cloud Group
     */
    cityCountry?: pulumi.Input<string>;
    /**
     * - Country code of the Private Cloud Group
     */
    countryCode?: pulumi.Input<string>;
    /**
     * - Description of the Private Cloud Group
     */
    description?: pulumi.Input<string>;
    /**
     * - Whether this Private Cloud Group is enabled or not
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * - Whether the Private Cloud Group is public
     */
    isPublic?: pulumi.Input<string>;
    /**
     * - Latitude of the Private Cloud Group. Integer or decimal. With values in the range of -90 to 90
     */
    latitude?: pulumi.Input<string>;
    /**
     * - Location of the Private Cloud Group
     */
    location?: pulumi.Input<string>;
    /**
     * - Longitude of the Private Cloud Group. Integer or decimal. With values in the range of -180 to 180
     */
    longitude?: pulumi.Input<string>;
    /**
     * - Microtenant ID for the Private Cloud Group
     */
    microtenantId?: pulumi.Input<string>;
    /**
     * - Name of the Private Cloud Group
     */
    name?: pulumi.Input<string>;
    /**
     * - Whether the default version profile of the Private Cloud Group is applied or overridden
     */
    overrideVersionProfile?: pulumi.Input<boolean>;
    /**
     * - Site ID for the Private Cloud Group
     */
    siteId?: pulumi.Input<string>;
    /**
     * - Private Cloud Controllers in this group will attempt to update to a newer version of the software during this specified day. Supported values: `SUNDAY`, `MONDAY`, `TUESDAY`, `WEDNESDAY`, `THURSDAY`, `FRIDAY`, `SATURDAY`
     */
    upgradeDay?: pulumi.Input<string>;
    /**
     * - Private Cloud Controllers in this group will attempt to update to a newer version of the software during this specified time. Integer in seconds (i.e., -66600). The integer should be greater than or equal to 0 and less than 86400, in 15 minute intervals
     */
    upgradeTimeInSecs?: pulumi.Input<string>;
    /**
     * - ID of the version profile for the Private Cloud Group
     */
    versionProfileId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a PrivateCloudGroup resource.
 */
export interface PrivateCloudGroupArgs {
    /**
     * - City and country of the Private Cloud Group
     */
    cityCountry?: pulumi.Input<string>;
    /**
     * - Country code of the Private Cloud Group
     */
    countryCode?: pulumi.Input<string>;
    /**
     * - Description of the Private Cloud Group
     */
    description?: pulumi.Input<string>;
    /**
     * - Whether this Private Cloud Group is enabled or not
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * - Whether the Private Cloud Group is public
     */
    isPublic?: pulumi.Input<string>;
    /**
     * - Latitude of the Private Cloud Group. Integer or decimal. With values in the range of -90 to 90
     */
    latitude?: pulumi.Input<string>;
    /**
     * - Location of the Private Cloud Group
     */
    location?: pulumi.Input<string>;
    /**
     * - Longitude of the Private Cloud Group. Integer or decimal. With values in the range of -180 to 180
     */
    longitude?: pulumi.Input<string>;
    /**
     * - Microtenant ID for the Private Cloud Group
     */
    microtenantId?: pulumi.Input<string>;
    /**
     * - Name of the Private Cloud Group
     */
    name?: pulumi.Input<string>;
    /**
     * - Whether the default version profile of the Private Cloud Group is applied or overridden
     */
    overrideVersionProfile?: pulumi.Input<boolean>;
    /**
     * - Site ID for the Private Cloud Group
     */
    siteId?: pulumi.Input<string>;
    /**
     * - Private Cloud Controllers in this group will attempt to update to a newer version of the software during this specified day. Supported values: `SUNDAY`, `MONDAY`, `TUESDAY`, `WEDNESDAY`, `THURSDAY`, `FRIDAY`, `SATURDAY`
     */
    upgradeDay?: pulumi.Input<string>;
    /**
     * - Private Cloud Controllers in this group will attempt to update to a newer version of the software during this specified time. Integer in seconds (i.e., -66600). The integer should be greater than or equal to 0 and less than 86400, in 15 minute intervals
     */
    upgradeTimeInSecs?: pulumi.Input<string>;
    /**
     * - ID of the version profile for the Private Cloud Group
     */
    versionProfileId?: pulumi.Input<string>;
}
