// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zpa from "@bdzscaler/pulumi-zpa";
 *
 * // ZPA Segment Group resource
 * const testSegmentGroup = new zpa.SegmentGroup("testSegmentGroup", {
 *     description: "test1-segment-group",
 *     enabled: true,
 * });
 * ```
 *
 * ## Import
 *
 * Zscaler offers a dedicated tool called Zscaler-Terraformer to allow the automated import of ZPA configurations into Terraform-compliant HashiCorp Configuration Language.
 *
 * Visit
 *
 * **segment_group** can be imported by using `<SEGMENT GROUP ID>` or `<SEGMENT GROUP NAME>` as the import ID.
 *
 * For example:
 *
 * ```sh
 * $ pulumi import zpa:index/segmentGroup:SegmentGroup example <segment_group_id>
 * ```
 *
 * or
 *
 * ```sh
 * $ pulumi import zpa:index/segmentGroup:SegmentGroup example <segment_group_name>
 * ```
 */
export class SegmentGroup extends pulumi.CustomResource {
    /**
     * Get an existing SegmentGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SegmentGroupState, opts?: pulumi.CustomResourceOptions): SegmentGroup {
        return new SegmentGroup(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'zpa:index/segmentGroup:SegmentGroup';

    /**
     * Returns true if the given object is an instance of SegmentGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SegmentGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SegmentGroup.__pulumiType;
    }

    public readonly applications!: pulumi.Output<outputs.SegmentGroupApplication[]>;
    /**
     * Description of the app group.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * Whether this app group is enabled or not.
     */
    public readonly enabled!: pulumi.Output<boolean | undefined>;
    public readonly microtenantId!: pulumi.Output<string>;
    /**
     * Name of the app group.
     */
    public readonly name!: pulumi.Output<string>;

    /**
     * Create a SegmentGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: SegmentGroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SegmentGroupArgs | SegmentGroupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SegmentGroupState | undefined;
            resourceInputs["applications"] = state ? state.applications : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["enabled"] = state ? state.enabled : undefined;
            resourceInputs["microtenantId"] = state ? state.microtenantId : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
        } else {
            const args = argsOrState as SegmentGroupArgs | undefined;
            resourceInputs["applications"] = args ? args.applications : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["enabled"] = args ? args.enabled : undefined;
            resourceInputs["microtenantId"] = args ? args.microtenantId : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SegmentGroup.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SegmentGroup resources.
 */
export interface SegmentGroupState {
    applications?: pulumi.Input<pulumi.Input<inputs.SegmentGroupApplication>[]>;
    /**
     * Description of the app group.
     */
    description?: pulumi.Input<string>;
    /**
     * Whether this app group is enabled or not.
     */
    enabled?: pulumi.Input<boolean>;
    microtenantId?: pulumi.Input<string>;
    /**
     * Name of the app group.
     */
    name?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SegmentGroup resource.
 */
export interface SegmentGroupArgs {
    applications?: pulumi.Input<pulumi.Input<inputs.SegmentGroupApplication>[]>;
    /**
     * Description of the app group.
     */
    description?: pulumi.Input<string>;
    /**
     * Whether this app group is enabled or not.
     */
    enabled?: pulumi.Input<boolean>;
    microtenantId?: pulumi.Input<string>;
    /**
     * Name of the app group.
     */
    name?: pulumi.Input<string>;
}
